window.livedesk._=function(m){return window.livedesk.i18n&&void 0!==window.livedesk.i18n[m]?window.livedesk.i18n[m]:m};
window.livedesk.loadGizmo=function(m){var q=this;(function(d){function p(a,f){var c=(a&65535)+(f&65535);return(a>>16)+(f>>16)+(c>>16)<<16|c&65535}function r(a,f,c,b,e,d){a=p(p(f,a),p(b,d));return p(a<<e|a>>>32-e,c)}function b(a,f,c,b,e,d,n){return r(f&c|~f&b,a,f,e,d,n)}function e(a,f,c,b,e,d,n){return r(f&b|c&~b,a,f,e,d,n)}function n(a,f,c,b,e,d,n){return r(c^(f|~b),a,f,e,d,n)}function D(a,f){a[f>>5]|=128<<f%32;a[(f+64>>>9<<4)+14]=f;var c,d,l,m,s,h=1732584193,g=-271733879,j=-1732584194,k=271733878;
for(c=0;c<a.length;c+=16)d=h,l=g,m=j,s=k,h=b(h,g,j,k,a[c],7,-680876936),k=b(k,h,g,j,a[c+1],12,-389564586),j=b(j,k,h,g,a[c+2],17,606105819),g=b(g,j,k,h,a[c+3],22,-1044525330),h=b(h,g,j,k,a[c+4],7,-176418897),k=b(k,h,g,j,a[c+5],12,1200080426),j=b(j,k,h,g,a[c+6],17,-1473231341),g=b(g,j,k,h,a[c+7],22,-45705983),h=b(h,g,j,k,a[c+8],7,1770035416),k=b(k,h,g,j,a[c+9],12,-1958414417),j=b(j,k,h,g,a[c+10],17,-42063),g=b(g,j,k,h,a[c+11],22,-1990404162),h=b(h,g,j,k,a[c+12],7,1804603682),k=b(k,h,g,j,a[c+13],12,
-40341101),j=b(j,k,h,g,a[c+14],17,-1502002290),g=b(g,j,k,h,a[c+15],22,1236535329),h=e(h,g,j,k,a[c+1],5,-165796510),k=e(k,h,g,j,a[c+6],9,-1069501632),j=e(j,k,h,g,a[c+11],14,643717713),g=e(g,j,k,h,a[c],20,-373897302),h=e(h,g,j,k,a[c+5],5,-701558691),k=e(k,h,g,j,a[c+10],9,38016083),j=e(j,k,h,g,a[c+15],14,-660478335),g=e(g,j,k,h,a[c+4],20,-405537848),h=e(h,g,j,k,a[c+9],5,568446438),k=e(k,h,g,j,a[c+14],9,-1019803690),j=e(j,k,h,g,a[c+3],14,-187363961),g=e(g,j,k,h,a[c+8],20,1163531501),h=e(h,g,j,k,a[c+13],
5,-1444681467),k=e(k,h,g,j,a[c+2],9,-51403784),j=e(j,k,h,g,a[c+7],14,1735328473),g=e(g,j,k,h,a[c+12],20,-1926607734),h=r(g^j^k,h,g,a[c+5],4,-378558),k=r(h^g^j,k,h,a[c+8],11,-2022574463),j=r(k^h^g,j,k,a[c+11],16,1839030562),g=r(j^k^h,g,j,a[c+14],23,-35309556),h=r(g^j^k,h,g,a[c+1],4,-1530992060),k=r(h^g^j,k,h,a[c+4],11,1272893353),j=r(k^h^g,j,k,a[c+7],16,-155497632),g=r(j^k^h,g,j,a[c+10],23,-1094730640),h=r(g^j^k,h,g,a[c+13],4,681279174),k=r(h^g^j,k,h,a[c],11,-358537222),j=r(k^h^g,j,k,a[c+3],16,-722521979),
g=r(j^k^h,g,j,a[c+6],23,76029189),h=r(g^j^k,h,g,a[c+9],4,-640364487),k=r(h^g^j,k,h,a[c+12],11,-421815835),j=r(k^h^g,j,k,a[c+15],16,530742520),g=r(j^k^h,g,j,a[c+2],23,-995338651),h=n(h,g,j,k,a[c],6,-198630844),k=n(k,h,g,j,a[c+7],10,1126891415),j=n(j,k,h,g,a[c+14],15,-1416354905),g=n(g,j,k,h,a[c+5],21,-57434055),h=n(h,g,j,k,a[c+12],6,1700485571),k=n(k,h,g,j,a[c+3],10,-1894986606),j=n(j,k,h,g,a[c+10],15,-1051523),g=n(g,j,k,h,a[c+1],21,-2054922799),h=n(h,g,j,k,a[c+8],6,1873313359),k=n(k,h,g,j,a[c+15],
10,-30611744),j=n(j,k,h,g,a[c+6],15,-1560198380),g=n(g,j,k,h,a[c+13],21,1309151649),h=n(h,g,j,k,a[c+4],6,-145523070),k=n(k,h,g,j,a[c+11],10,-1120210379),j=n(j,k,h,g,a[c+2],15,718787259),g=n(g,j,k,h,a[c+9],21,-343485551),h=p(h,d),g=p(g,l),j=p(j,m),k=p(k,s);return[h,g,j,k]}function l(a){var f,c="";for(f=0;f<32*a.length;f+=8)c+=String.fromCharCode(a[f>>5]>>>f%32&255);return c}function H(a){var f,c=[];c[(a.length>>2)-1]=void 0;for(f=0;f<c.length;f+=1)c[f]=0;for(f=0;f<8*a.length;f+=8)c[f>>5]|=(a.charCodeAt(f/
8)&255)<<f%32;return c}function v(a,f){var c,b=H(a),e=[],d=[];e[15]=d[15]=void 0;16<b.length&&(b=D(b,8*a.length));for(c=0;16>c;c+=1)e[c]=b[c]^909522486,d[c]=b[c]^1549556828;c=D(e.concat(H(f)),512+8*f.length);return l(D(d.concat(c),640))}function B(a){var f="",c,b;for(b=0;b<a.length;b+=1)c=a.charCodeAt(b),f+="0123456789abcdef".charAt(c>>>4&15)+"0123456789abcdef".charAt(c&15);return f}function A(a){a=unescape(encodeURIComponent(a));return l(D(H(a),8*a.length))}function s(a,f){var c;if("undefined"==
typeof a||"undefined"==typeof f)return!0;for(c in f)if("undefined"==typeof a[c])return!0;for(c in a)if("undefined"==typeof f[c])return!0;for(c in f)if(f[c])switch(typeof f[c]){case "object":if(s(f[c],a[c]))return!0;break;case "function":if("undefined"==typeof a[c]||f[c].toString()!=a[c].toString())return!0;break;default:if(f[c]!=a[c])return!0}else if(a[c])return!0;return!1}str=function(a){this.init(a)};str.format=function(a){var f=arguments,c=1;2==f.length&&"object"==typeof f[1]&&(f=f[1]);return a.replace(/%?%(?:\(([^\)]+)\))?([disr])/g,
function(a,b,e){if(a[0]==a[1])return a.substring(1);b=f[b||c++];return"undefined"===typeof b?a:"i"==e||"d"==e?+b:b})};str.prototype={init:function(a){this.str=a},format:function(){return str.format(this.str)},toString:function(){return this.str}};d.md5=function(a,f,c){return!f?c?A(a):B(A(a)):c?v(unescape(encodeURIComponent(f)),unescape(encodeURIComponent(a))):B(v(unescape(encodeURIComponent(f)),unescape(encodeURIComponent(a))))};var y={url:"//gravatar.com/avatar/%(md5)s?r=%(rate)s&s=%(size)s&d=%(default)s&%(forcedefault)s",
defaults:{rate:"pg",size:48,"default":encodeURIComponent("images/avatar_default_collaborator.png"),forcedefault:"",key:"Avatar",needle:"Person.EMail"},parse:function(a,f){if(a){f||(f=this.defaults.needle);var c=this,b=f.split("."),e=b[0],n=b[1];d.each(a,function(a,b){a===e&&(void 0!==n&&d.isDefined(b[n]))&&(this[c.defaults.key]=c.get(b[n]));(d.isObject(b)||d.isArray(b))&&c.parse(b,f)});return a}},get:function(a){return"string"!==d.type(a)?a:str.format(this.url,d.extend({},this.defaults,{md5:d.md5(d.trim(a.toLowerCase()))}))}};
d.avatar=y;var u,Q=/d{1,4}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|[LloSZ]|"[^"]*"|'[^']*'/g,R=/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g,S=/[^-+\dA-Z]/g,x=function(a,f){a=String(a);for(f=f||2;a.length<f;)a="0"+a;return a};u=function(a,f,c){1==arguments.length&&("[object String]"==Object.prototype.toString.call(a)&&!/\d/.test(a))&&(f=a,a=void 0);a=a?new Date(a):new Date;if(isNaN(a))throw SyntaxError("invalid date");
f=String(u.masks[f]||f||u.masks["default"]);"UTC:"==f.slice(0,4)&&(f=f.slice(4),c=!0);var b=c?"getUTC":"get",e=a[b+"Date"](),d=a[b+"Day"](),n=a[b+"Month"](),h=a[b+"FullYear"](),g=a[b+"Hours"](),j=a[b+"Minutes"](),k=a[b+"Seconds"](),b=a[b+"Milliseconds"](),l=c?0:a.getTimezoneOffset(),m={d:e,dd:x(e),ddd:u.i18n.dayNames[d],dddd:u.i18n.dayNames[d+7],m:n+1,mm:x(n+1),mmm:u.i18n.monthNames[n],mmmm:u.i18n.monthNames[n+12],yy:String(h).slice(2),yyyy:h,h:g%12||12,hh:x(g%12||12),H:g,HH:x(g),M:j,MM:x(j),s:k,
ss:x(k),l:x(b,3),L:x(99<b?Math.round(b/10):b),t:12>g?"a":"p",tt:12>g?"am":"pm",T:12>g?"A":"P",TT:12>g?"AM":"PM",Z:c?"UTC":(String(a).match(R)||[""]).pop().replace(S,""),o:(0<l?"-":"+")+x(100*Math.floor(Math.abs(l)/60)+Math.abs(l)%60,4),S:["th","st","nd","rd"][3<e%10?0:(10!=e%100-e%10)*e%10]};return f.replace(Q,function(a){return a in m?m[a]:a.slice(1,a.length-1)})};u.masks={"default":"ddd mmm dd yyyy HH:MM:ss",shortDate:"m/d/yy",mediumDate:"mmm d, yyyy",longDate:"mmmm d, yyyy",fullDate:"dddd, mmmm d, yyyy",
shortTime:"h:MM TT",mediumTime:"h:MM:ss TT",longTime:"h:MM:ss TT Z",isoDate:"yyyy-mm-dd",isoTime:"HH:MM:ss",isoDateTime:"yyyy-mm-dd'T'HH:MM:ss",isoUtcDateTime:"UTC:yyyy-mm-dd'T'HH:MM:ss'Z'"};u.i18n={dayNames:"Sun Mon Tue Wed Thu Fri Sat Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),monthNames:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec January February March April May June July August September October November December".split(" ")};window.livedesk.i18n&&void 0!==window.livedesk.i18n.day_names&&
(u.i18n.dayNames=window.livedesk.i18n.day_names);window.livedesk.i18n&&void 0!==window.livedesk.i18n.month_names&&(u.i18n.monthNames=window.livedesk.i18n.month_names);Date.prototype.format=function(a,f){return u(this,a,f)};Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});Function.prototype.bind||(Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");
var f=Array.prototype.slice.call(arguments,1),c=this,b=function(){},e=function(){return c.apply(this instanceof b?this:a,f.concat(Array.prototype.slice.call(arguments)))};b.prototype=this.prototype;e.prototype=new b;return e});String.prototype.trim||(String.prototype.trim=function(){for(var a=this.replace(/^\s\s*/,""),f=/\s/,c=a.length;f.test(a.charAt(--c)););return a.slice(0,c+1)});var I=!1;this.Class=function(){};Class.extend=function(a,f){function c(){if(!I&&(this._constructor||this._construct))try{return(this._construct||
this._constructor).apply(this,arguments)}catch(a){}}I=!0;var b=new this;I=!1;for(var e in a)b[e]=a[e];c.prototype=b;c.prototype.constructor=c;c.extend=arguments.callee;return c};var K=function(){},t=function(){},L=function(){this.items={}},w=function(){},M=Class.extend({_construct:function(a){this.data=!this.data?{root:""}:this.data;switch(d.type(a)){case "string":this.data.url=a;break;case "array":this.data.url=a[0];void 0!==a[1]&&(this.data.xfilter=url[0]);break;case "object":this.data.url=a.url,
void 0!==a.xfilter&&(this.data.xfilter=a.xfilter)}return this},xfilter:function(){this.data.xfilter=1<arguments.length?d.makeArray(arguments).join(","):d.isArray(arguments[0])?arguments[0].join(","):arguments[0];return this},root:function(a){this.data.root=a;return this},get:function(){return this.data.root+this.data.url},order:function(a,f){this.data.order=f+"="+a;return this},filter:function(a,f){this.data.filter=a+"="+f;return this},decorate:function(a){this.data.url=a.replace(/(%s)/g,this.data.url)},
options:function(){var a={};this.data.xfilter&&(a.headers={"X-Filter":this.data.xfilter});return a}}),z={request:function(a){var f=this,c=function(c,b,e){d.support.cors=!0;a instanceof M?(b=d.extend(!0,{},b,f.options,e,{data:c},a.options()),c=d.ajax(f.href(a.get()),b)):(b=d.extend(!0,{},b,f.options,e,{data:c}),c=d.ajax(f.href(a),b));f.reset();b.fail&&c.fail(b.fail);b.done&&c.done(b.done);b.always&&c.always(b.always);return c};return{read:function(a){return c({},f.readOptions,a)},update:function(a,
b){return c(a,f.updateOptions,b)},insert:function(a,b){return c(a,f.insertOptions,b)},remove:function(a){return c({},f.removeOptions,a)}}},href:function(a){return a},reset:d.noop,options:{},readOptions:{dataType:"json",type:"get",headers:{Accept:"text/json"}},updateOptions:{type:"post",headers:{"X-HTTP-Method-Override":"PUT"}},insertOptions:{dataType:"json",type:"post"},removeOptions:{type:"get",headers:{"X-HTTP-Method-Override":"DELETE"}}},T=0;t.prototype={_changed:!1,_new:!1,defaults:{},data:{},
_construct:function(a,b){this._clientId=T++;this.data={};this.parseHash(a);this._new=!0;var c=this.pushUnique?this.pushUnique():this;c._forDelete=!1;c.clearChangeset();c._clientHash=null;b&&"object"==typeof b&&d.extend(c,b);"object"==typeof a&&(c._parse(a),c._setExpiration());d.isEmptyObject(c.changeset)||(c.triggerHandler("update",c.changeset),c.clearChangeset());return c},syncAdapter:z,feed:function(a,b,c){var a={},c=c?c:this.data,e;for(e in c)a[e]=c[e]instanceof t?b?c[e].feed(b):c[e].relationHash()||
c[e].hash():c[e];return a},sync:function(a,b){var c=this,e=d.Deferred(),n=function(){return c.syncAdapter.request.apply(c.syncAdapter,arguments)};this.hash();c.triggerHandler("sync");if(this._forDelete)return n(a||this.href).remove().done(function(){c._remove()});if(this._clientHash)return n(a||this.href).insert(this.feed()).done(function(a){c._changed=!1;c._parse(a);c._uniq&&c._uniq.replace(c._clientHash,c.hash(),c);c._clientHash=null;c.triggerHandler("insert").Class.triggerHandler("insert",c)});
this._changed?d.isEmptyObject(this.changeset)||(e=this.href&&n(this.href).update(b?this.feed():this.feed("json",!1,this.changeset)).done(function(){c.triggerHandler("update",c.changeset).clearChangeset()})):(!a||!a.force)&&this.exTime&&this.exTime>new Date?c.isDeleted()||c.triggerHandler("update"):e=this.href&&n(this.href).read(a).done(function(a){c._parse(a);c.isDeleted()?c._remove():d.isEmptyObject(c.changeset)?c.clearChangeset().triggerHandler("read"):c.triggerHandler("update",c.changeset).clearChangeset()});
this._setExpiration();return e},_setExpiration:function(){this.exTime=new Date;this.exTime.setSeconds(this.exTime.getSeconds()+5)},_remove:function(){this.triggerHandler("delete");this._uniq&&this._uniq.remove(this.hash())},remove:function(){this._forDelete=!0;return this},isDeleted:function(){return this._forDelete},modelDataBuild:function(a){return a},parse:function(a){return a},_parse:function(a){a=a instanceof t?a.data:this.parse(a);if(!a._parsed){for(var b in a){if(this.defaults[b])switch(!0){case "function"===
typeof this.defaults[b]&&void 0===this.data[b]:var c=this.modelDataBuild(new this.defaults[b](a[b]));!this._new&&(c!=this.data[b]&&!(c instanceof w))&&(this.changeset[b]=c);this.data[b]=c;!a[b].href&&this.data[b].relationHash&&this.data[b].relationHash(a[b]);continue;case d.isArray(this.defaults[b]):this.data[b]=this.modelDataBuild(new w(this.defaults[b][0],a[b].href));delete this.data[b];continue;case this.defaults[b]instanceof w:case this.defaults[b]instanceof t:this.data[b]=this.defaults[b];continue}else this._new||
("object"===d.type(a[b])?s(this.data[b],a[b])&&(this.changeset[b]=a[b]):this.data[b]!=a[b]&&(this.changeset[b]=a[b]));"object"===d.type(a[b])&&"object"===d.type(this.data[b])?d.extend(!0,this.data[b],a[b]):this.data[b]=a[b]}this._new=!1;a._parsed=!0}},parseHash:function(a){if(a instanceof t)return this;"string"==typeof a?this.href=a:a&&void 0!==a.href?(this.href=a.href,delete a.href):a&&(void 0!==a.id&&void 0!==this.url)&&(this.href=this.url+a.id);return this},clearChangeset:function(){this._changed=
!1;this.changeset={};return this},get:function(a){return this.data[a]},set:function(a,b,c){var e={};"string"===d.type(a)?e[a]=b:(e=a,c=b);c=d.extend({},{silent:!1},c);this.clearChangeset()._parse(e);this._changed=!0;d.isEmptyObject(this.changeset)||c.silent||this.triggerHandler("set",this.changeset);return this},_getClientHash:function(){this._clientHash||(this._clientHash="mcid-"+String(this._clientId));return this._clientHash},hash:function(){!this.href&&this.data.href&&(this.href=this.data.href);
return this.data.href||this.href||this._getClientHash()},relationHash:function(a){a&&(this.data.Id=a);return this.data.Id},off:function(a,b){d(this).off(a,b);return this},on:function(a,b,c){if(void 0===c)d(this).off(a,b),d(this).on(a,b);else d(this).on(a,function(){b.apply(c,arguments)});return this},trigger:function(a,b){d(this).trigger(a,b);return this},triggerHandler:function(a,b){d(this).triggerHandler(a,b);return this}};L.prototype={items:{},garbageTime:1500,refresh:function(a){a._exTime||(a._exTime=
new Date);a._exTime.setTime(a._exTime.getTime()+this.garbageTime)},set:function(a,b){var c=this;d(b).on("sync get get-prop set-prop",function(){c.refresh(this)});c.refresh(b);this.items[a]||(this.items[a]=b);return this.items[a]},replace:function(a,b,c){delete this.items[a];return this.set(b,c)},garbage:function(){for(var a in this.items)this.items[a]._exTime&&this.items[a]._exTime<new Date&&(d(this.items[a]).triggerHandler("garbage"),delete this.items[a])},remove:function(a){delete this.items[a]}};
var C=t.options={},N,O;t.extend=N=function(a,b){var c;c=Class.extend.call(this,a);c.extend=N;c.prototype.Class=c;c.on=function(a,b,f){d(c).on(a,function(){b.apply(f,arguments)});return c};c.off=function(a,b){d(c).off(a,b);return c};c.triggerHandler=function(a,b){d(c).triggerHandler(a,b)};b&&b.register&&(K[b.register]=c,delete b.register);c.prototype.options=d.extend({},b);return c};w.prototype={_list:[],getList:function(){return this._list},count:function(){return this._list.length},_construct:function(){this.model||
(this.model=t);this._list=[];this.desynced=!0;var a=buildOptions=function(){void 0},b;for(b in arguments)switch(d.type(arguments[b])){case "function":this.model=arguments[b];break;case "string":this.href=arguments[b];break;case "array":a=function(a){return function(){this._list=this._parse(a)}}(arguments[b]);break;case "object":buildOptions=function(a){return function(){this.options=a;a.href&&(this.href=a.href)}}(arguments[b])}buildOptions.call(this);a.call(this);C=d.extend({},{init:!0},this.options);
C.init&&this.init.apply(this,arguments)},init:function(){},get:function(a){var b=d.Deferred(),c=this;searchKey=function(){for(var e=0;e<c._list.length;e++)if(a==c._list[e].hash()||a==c._list[e].relationHash())return b.resolve(c._list[e]);b.reject()};this.desynced&&this.sync().done(function(){b.resolve(searchKey())})?b:searchKey();return b},remove:function(a){for(var b in this._list)if(a==this._list[b].hash()||a==this._list[b].relationHash()){Array.prototype.splice.call(this._list,b,1);break}return this},
syncAdapter:z,setHref:function(a){this.href=a;return this},each:function(a){d.each(this._list,a)},forwardEach:function(a,b){this._list.forEach(a,b)},reverseEach:function(a,b){for(var c=this._list.length;0<c;++c)a.call(b||this,this[c],c,this)},feed:function(a,b){var c=[],e;for(e in this._list)c[e]=this._list[e].feed(a,b);return c},sync:function(a){var b=this;return this.href&&this.syncAdapter.request.call(this.syncAdapter,this.href).read(a).done(function(a){for(var a=b._parse(a),e=[],d=[],n=b._list.length,
l=0;l<a.length;l++){for(var h=!1,g=0;g<n;g++)if(a[l].hash()==b._list[g].hash()){h=a[l];break}if(h)if(d.push(h),h.isDeleted())h._remove();else h.on("delete",function(){b.remove(this.hash())}).on("garbage",function(){this.desynced=!0});else a[l].isDeleted()?d.push(a[l]):(b._list.push(a[l]),e.push(a[l]))}b.desynced=!1;0===n?b.triggerHandler("read"):(b.triggerHandler("updates",[d]),b.triggerHandler("addings",[e]))})},modelDataBuild:function(a){return a},parse:function(a){var b=a;if(!Array.isArray(a))for(i in a)if(d.isArray(a[i])){b=
a[i];break}return b},_parse:function(a){if(a._parsed)return a._parsed;var a=this.parse(a),b,c=[],e;for(b in a)a.hasOwnProperty(b)&&(e=new this.model(a[b]),e=this.modelDataBuild(e),c.push(e));a._parsed=c;return a._parsed},insert:function(a){this.desynced=!1;a instanceof t||(a=this.modelDataBuild(new this.model(a)));this._list.push(a);a.hash();return a.sync(this.href)},off:function(a,b){d(this).off(a,b);return this},on:function(a,b,c){if(void 0===c)d(this).off(a,b),d(this).on(a,b);else d(this).on(a,
function(){b.apply(c,arguments)});return this},trigger:function(a,b){d(this).trigger(a,b);return this},triggerHandler:function(a,b){d(this).triggerHandler(a,b);return this}};w.extend=O=function(a){a=Class.extend.call(this,a);a.extend=O;C&&C.register&&(w[C.register]=a);return a};var U=0,y=Class.extend({getProperty:function(a){return!this[a]?null:"function"===typeof this[a]?this[a]():this[a]}}).extend({tagName:"div",attributes:{className:"",id:""},namespace:"view",_constructor:function(a,b){d.extend(this,
a);this._clientId=U++;b=d.extend({},{init:!0,events:!0,ensure:!0},b);b.ensure&&this._ensureElement();b.init&&this.init.apply(this,arguments);b.events&&this.resetEvents()},_ensureElement:function(){var a=this.attributes.className,b=this.attributes.id,c="";d(this.el).length?this.el=d(this.el):("string"===d.type(this.el)&&("."==this.el[0]&&(a+=this.el.substr(0,1)),"#"==this.el[0]&&(b=this.el.substr(0,1))),c="<"+this.tagName,""!==a&&(c=c+' class="'+a+'"'),""!==b&&(c=c+' id="'+b+'"'),c=c+"></"+this.tagName+
">",this.el=d(c))},init:function(){return this},resetEvents:function(){this.undelegateEvents();this.delegateEvents()},delegateEvents:function(a){if(a||(a=this.getProperty("events")))for(var b in a){var c=a[b],e;for(e in c){var n=c[e];if("string"===typeof n&&d.isFunction(this[n]))d(this.el).on(this.getEvent(e),b,this[n].bind(this))}}},undelegateEvents:function(){d(this.el).off(this.getNamespace());return this},getEvent:function(a){return a+this.getNamespace()},getNamespace:function(){return"."+this.getProperty("namespace")},
render:function(){this.delegateEvents();return this},remove:function(){d(this.el).remove();this.destroy();return this},destroy:function(){this.model&&this.model.trigger("destroy");this.collection&&this.collection.trigger("destroy");return this},checkElement:function(){return void 0===this.el?!1:void 0!==this.el.selector&&""!=this.el.selector?1===d(this.el.selector).length:d(this.el).is(":visible")},setElement:function(a){this.undelegateEvents();var a=d(a),b=this.el.data();this.el.replaceWith(a);this.el=
a;this.el.data(b);this.delegateEvents();return this},resetElement:function(a){this.el=d(a);this._ensureElement();this.delegateEvents()}}),P=t,J=w,z=d.extend({},z,{reset:function(){try{delete this.options.headers["X-Filter"],delete this.options.data["CId.since"],delete this.options.data.offset,delete this.options.data.limit}catch(a){}}}),V=function(){AuthApp.success=function(){};AuthApp.require.apply(this,arguments)},E=d.extend({},z,{options:{fail:function(a){401==a.status&&V.apply(E,arguments);404==
a.status&&ErrorApp.require.apply(this,arguments)}},href:function(a){return-1===a.indexOf("my/")?a.replace("resources/","resources/my/"):a}}),F=function(){this.syncAdapter.options.headers||(this.syncAdapter.options.headers={});this._xfilter=1<arguments.length?d.makeArray(arguments).join(","):d.isArray(arguments[0])?arguments[0].join(","):arguments[0];this.syncAdapter.options.headers["X-Filter"]=this._xfilter;this.syncAdapter.options.headers["X-Format-DateTime"]="M/dd/yyyy HH:mm:ss";return this},G=
function(a){a?d.extend(!0,this.syncAdapter.options,{data:{"CId.since":a}}):delete this.syncAdapter.options.data["CId.since"];return this},t=P.extend({isDeleted:function(){return this._forDelete||this.data.DeletedOn},syncAdapter:z,xfilter:F,since:G}),W=t.extend({syncAdapter:E,xfilter:F,since:G}),w=J.extend({xfilter:F,since:G,asc:function(a){d.extend(!0,this.syncAdapter.options,{data:{asc:a}});return this},desc:function(a){d.extend(!0,this.syncAdapter.options,{data:{desc:a}});return this},limit:function(a){d.extend(!0,
this.syncAdapter.options,{data:{limit:a}});return this},offset:function(a){d.extend(!0,this.syncAdapter.options,{data:{offset:a}});return this},syncAdapter:z}),J=w.extend({xfilter:F,since:G,syncAdapter:E});t.extend=function(){var a=P.extend.apply(this,arguments),b=new L;d.extend(a.prototype,{_uniq:b,pushUnique:function(){return b.set(this.hash(),this)}},arguments[0]);return a};d.gizmo={Model:t,AuthModel:W,Collection:w,AuthCollection:J,Sync:z,AuthSync:E,View:y,Url:M,Register:K};q.preLoad(m)})(jQuery)};
function isOnly(m,q){"string"===$.type(q)&&(q=[q]);var d=0,p=q.length;for(i in m){if(-1===$.inArray(i,q))return!1;d++;if(d>p)return!1}return d===p}var root=this;
window.livedesk.loadXDRequest=function(m){var q=m;root.XDomainRequest&&q.ajaxTransport("+*",function(d){if(d.crossDomain&&d.async){d.timeout&&(d.xdrTimeout=d.timeout,delete d.timeout);var m;return{send:function(r,b){function e(e,d,n,v){m.onload=m.onerror=m.ontimeout=q.noop;m=void 0;b(e,d,n,v)}m=new XDomainRequest;if(d.dataType){var n="";for(i in d.headers)n+=i+"="+encodeURIComponent(d.headers[i])+"&";n=n.replace(/(\s+)?.$/,"");d.url=d.url+(-1===d.url.indexOf("?")?"?":"&")+n}m.open(d.type,d.url);m.onload=
function(){e(200,"OK",{text:m.responseText},"Content-Type: "+m.contentType)};m.onerror=function(){e(404,"Not Found")};d.xdrTimeout&&(m.ontimeout=function(){e(0,"timeout")},m.timeout=d.xdrTimeout);m.send(d.hasContent&&d.data||null)},abort:function(){m&&(m.onerror=q.noop(),m.abort())}}}})};
window.livedesk.init=function(){window.livedesk.location=window.location.href.split("#")[0];var m=this;contentPath=void 0===m.contentPath?"":m.contentPath;m.loadScript("//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js",function(){m.loadXDRequest(jQuery);"undefined"==typeof $.gizmo?m.loadGizmo(!1):m.preLoad(!1)})};
window.livedesk.loadScript=function(m,q){var d=document.createElement("script");d.type="text/javascript";d.readyState?d.onreadystatechange=function(){if("loaded"==d.readyState||"complete"==d.readyState)d.onreadystatechange=null,q()}:d.onload=function(){q()};d.src=m;document.getElementsByTagName("head")[0].appendChild(d)};window.livedesk.preLoad=function(m){m?(m=$.noConflict(!0),this.startLoading(m,window.livedesk._)):this.startLoading(jQuery,window.livedesk._)};
window.livedesk.startLoading=function(m,q){var d=m.gizmo.Model.extend({}),d=m.gizmo.Model.extend({defaults:{Creator:d},services:{flickr:!0,google:!0,twitter:!0,facebook:!0,youtube:!0},getClass:function(){switch(this.get("Type").Key){case "wrapup":return"wrapup";case "quote":return"quotation";case "advertisement":return"advertisement";default:return this.isService()?"service":"tw"}},isService:function(){return this.get("AuthorName")in this.services},isQuote:function(){return"quotation"==this.getClass()},
twitter:{link:{anchor:function(b){return b.replace(/[A-Za-z]+:\/\/[A-Za-z0-9-_]+\.[A-Za-z0-9-_:%&\?\/.=]+/g,function(b){b=b.link(b);return b=b.replace('href="','target="_blank" href="')})},user:function(b){return b.replace(/[@]+[A-Za-z0-9-_]+/g,function(b){var d=b.replace("@",""),b=b.link("http://twitter.com/"+d);return b=b.replace('href="','target="_blank" onclick="loadProfile(\''+d+'\');return(false);"  href="')})},tag:function(b){return b.replace(/[#]+[A-Za-z0-9-_]+/g,function(b){var d=b.replace(" #",
" %23"),b=b.link("http://summize.com/search?q="+d);return b=b.replace('href="','target="_blank" href="')})},all:function(b){b=this.anchor(b);b=this.user(b);return b=this.tag(b)}}}});Posts=m.gizmo.Collection.extend({timeInterval:1E4,idInterval:0,_latestCId:0,keep:!1,init:function(){var b=this;this.on("readauto updates",function(e,d){void 0===d&&(d=b._list);b.getMaximumCid(d)})},destroy:function(){this.stop()},auto:function(){var b=this;ret=this.stop().start();this.idInterval=setInterval(function(){b.start()},
this.timeInterval);return ret},getMaximumCid:function(b){p=0;for(count=b.length;p<count;p++){var e=parseInt(b[p].get("CId"));!isNaN(e)&&this._latestCId<e&&(this._latestCId=e)}},start:function(){var b={data:{"cId.since":this._latestCId},headers:{"X-Filter":this._xfilter,"X-Format-DateTime":"M/dd/yyyy HH:mm:ss"}};0===this._latestCId&&delete b.data;if(!this.keep&&this.view&&!this.view.checkElement())this.stop();else return this.triggerHandler("beforeUpdate"),this.autosync(b)},stop:function(){clearInterval(this.idInterval);
return this},autosync:function(b){var e=this;return this.href&&this.syncAdapter.request.call(this.syncAdapter,this.href).read(b).done(function(b){for(var b=e._parse(b),d=[],l=[],m=e._list.length,q=0;q<b.length;q++){for(var p=!1,r=0;r<m;r++)if(b[q].hash()==e._list[r].hash()){p=b[q];break}if(p)if(l.push(p),p.isDeleted())p._remove();else p.on("delete",function(){e.remove(this.hash())}).on("garbage",function(){this.desynced=!0});else b[q].isDeleted()?l.push(b[q]):(e._list.push(b[q]),d.push(b[q]))}e.desynced=
!1;0===m?e.triggerHandler("readauto"):(e.triggerHandler("updatesauto",[l]),e.triggerHandler("addingsauto",[d]))})}}).extend({parse:function(b){void 0!==b.total&&(b.total=parseInt(b.total),void 0===this.total&&(this.total=b.total),delete b.total);return b.PostList?b.PostList:b},model:d});Blog=m.gizmo.Model.extend({defaults:{PostPublished:Posts}});var p=0,r;r=m.gizmo.View.extend({init:function(){var b=this;b.xfilter="PublishedOn, DeletedOn, Order, Id, CId, Content, CreatedOn, Type, AuthorName, Author.Source.Name, Author.Source.Id, IsModified, AuthorPerson.EMail, AuthorPerson.FirstName, AuthorPerson.LastName, AuthorPerson.Id, Meta";
b.model.on("read update",function(e,d){b.render(e,d)}).on("delete",b.remove,b).xfilter(b.xfilter).sync()},remove:function(){this._parent.removeOne(this);this.el.remove();return this},itemTemplate:function(b,e,d,m){var l="",p=b.getClass(),r=b.get("AuthorName"),B="",A="";if(b.data.hasOwnProperty("Meta")){var s=b.data.Meta;"string"==typeof s&&(s=JSON.parse(s));if(s.hasOwnProperty("annotation"))if("string"===typeof s.annotation){if("<br>"===s.annotation||"<br/>"===s.annotation||"<br />"===s.annotation)s.annotation=
"";A='<div class="editable annotation">'+s.annotation+"</div>"}else if(null!==s.annotation[1]){if("<br>"===s.annotation[0]||"<br/>"===s.annotation[0]||"<br />"===s.annotation[0])s.annotation[0]="";if("<br>"===s.annotation[1]||"<br/>"===s.annotation[1]||"<br />"===s.annotation[1])s.annotation[1]="";B='<div class="editable annotation">'+s.annotation[0]+"</div>";A='<div class="editable annotation">'+s.annotation[1]+"</div>"}else{if("<br>"===s.annotation[0]||"<br/>"===s.annotation[0]||"<br />"===s.annotation[0])s.annotation[0]=
"";A='<div class="editable annotation">'+s.annotation[0]+"</div>"}}avatarString="";"true"!=q("no_avatar")&&(0<m.length&&"twitter"!=r)&&(avatarString='<figure><img src="'+m+'" ></figure>');switch(p){case "tw":case "service":l=l+B+avatarString;l+='<div class="result-content">';"twitter"==r?(l+='<blockquote class="twitter-tweet"><p>'+e+"</p>&mdash; "+s.from_user_name+" (@"+s.from_user_name+') <a href="https://twitter.com/'+s.from_user+"/status/"+s.id_str+'" data-datetime="'+s.created_at+'"></a></blockquote>',
window.livedesk.loadScript("//platform.twitter.com/widgets.js",function(){}),window.livedesk.loadedTweeterScript=!0):"youtube"==r?(l+='<div class="result-text">'+e+"</div>",l+='<p class="attributes"><i class="source-icon"></i> '+q("by")+" ",l+='<a class="author-name" href="http://youtube.com/'+s.uploader+'" target="_blank">'+s.uploader+"</a>"):"google"==r?(l+='<h3><a target="_blank" href="'+s.unescapedUrl+'">'+s.title+"</a></h3>",l+='<div class="result-text">'+e+"</div>",l+='<p class="attributes"><i class="source-icon"></i> '+
q("by")+" "+b.get("AuthorName")):"flickr"==r?(l+='<div class="result-text">'+e+"</div>",l+='<p class="attributes"><i class="source-icon"></i> '+q("by")+" "+b.get("AuthorName")):(l+='<div class="result-text">'+e+"</div>",l+='<p class="attributes"><i class="source-icon"></i> '+q("by")+" "+b.get("AuthorName"),l+="<time>"+d+"</time>");l+="</p>";l+="</div>";l+=A;break;case "quotation":var y,b=b.get("AuthorName"),d=e.split("<div><br><br></div>"),m=e.split("<br><br><br>");2==d.length?(e=d[0],y='<div class="quotation-author">'+
d[1]+"</div>"):2==m.length&&(e=m[0],y='<div class="quotation-author">'+m[1]+"</div>");l+='<div class="result-content">';l+='<div class="result-text">'+e+"</div>";l=y?l+y:l+('<div class="attributes">'+q("by")+" "+b+"</div>");l+="</div>";break;case "wrapup":l+='<span class="big-toggle"></span>';l+="<h3>"+e+"</h3>";break;case "advertisement":l+=e}return l},toggleWrap:function(b,e){"boolean"!=typeof e&&(e=!1);this._toggleWrap(m(b).closest("li").first(),e)},_toggleWrap:function(b,e){"boolean"!=typeof e&&
(e=!1);if(b.hasClass("open")){var d=!0,q=window.location.hash;0<q.length&&!1==e&&b.nextUntil(".wrapup").each(function(){"#"+m(this).find("a").attr("name")==q&&(d=!1)});d&&(b.removeClass("open").addClass("closed"),b.nextUntil(".wrapup").hide())}else b.removeClass("closed").addClass("open"),b.nextUntil(".wrapup").show()},togglePermalink:function(b){this._togglePermalink(m(b).next('input[data-type="permalink"]'))},_togglePermalink:function(b){"visible"==b.css("visibility")?b.css("visibility","hidden"):
b.css("visibility","visible")},render:function(){countLoaded++;var b=this,e=parseFloat(b.model.get("Order")),d="";this.model.get("AuthorPerson")&&this.model.get("AuthorPerson").EMail&&(d=m.avatar.get(b.model.get("AuthorPerson").EMail));!isNaN(b.order)&&e!=b.order&&(b.order=e,b._parent.reorderOne(b));var p=b.model.get("Content"),e="";"wrapup"==b.model.getClass()&&(e+="open ");if(b.model.isService()){var e=e+b.model.get("AuthorName"),l=JSON.parse(b.model.get("Meta")),r=b.model.get("PublishedOn"),r=
new Date(r),v=r.format("ddd mmm dd yyyy HH:MM:ss TT");"flickr"==b.model.get("AuthorName")?(p=m("<span>"+p+"</span>"),p.find("img").attr("src",p.find("a").attr("href")),p=p.html()):"twitter"==b.model.get("AuthorName")?(d=l.profile_image_url,p=b.model.twitter.link.all(p)):"google"==b.model.get("AuthorName")&&l.tbUrl&&(p+='<p><a href="'+l.url+'"><img src="'+l.tbUrl+'" height="'+l.tbHeight+'" width="'+l.tbWidth+'"></a></p>')}r=b.model.get("PublishedOn");r=new Date(r);v=r.format(q("ddd mmm dd yyyy HH:MM:ss TT"));
"true"===q("show_current_date")&&(new Date).format("mm dd yyyy")==r.format("mm dd yyyy")&&(v=r.format(q("HH:MM:ss TT")));b.model.get("AuthorName");p=b.itemTemplate(b.model,p,v,d);l=b.model.get("Id");d=b._parent.model.get("Title");d=d.replace(/ /g,"-");d=l+"-"+encodeURI(d);d=l;l=b.model.getClass();r=window.livedesk.location+"#"+d;v="";"advertisement"!==l&&"wrapup"!==l&&(v='<a rel="bookmark" href="#'+d+'">#</a><input type="text" value="'+r+'" style="visibility:hidden" data-type="permalink" />');e='<li class="'+
e+l+'"><a name="'+d+'"></a>'+p+"&nbsp;"+v+"</li>";"undefined"!=typeof window.livedesk.productionServer&&"undefined"!=typeof window.livedesk.frontendServer&&(re=RegExp(window.livedesk.productionServer,"g"),e=e.replace(re,window.livedesk.frontendServer));b.setElement(e);b.model.triggerHandler("rendered");m(b.el).off("click.livedesk",".big-toggle").on("click.livedesk",".big-toggle",function(){b.toggleWrap(this,!0)});m(b.el).off("click.livedesk",'a[rel="bookmark"]').on("click.livedesk",'a[rel="bookmark"]',
function(){b.togglePermalink(this)});m(b.el).off("click.livedesk",'input[data-type="permalink"]').on("focus.livedesk click.livedesk",'input[data-type="permalink"]',function(){m(this).select()})}});countLoaded=iidLoadTrace=totalLoad=0;d=m.gizmo.View.extend({limit:25,offset:0,el:"#livedesk-root",timeInterval:1E4,idInterval:0,_latestCId:0,events:{"#liveblog-more":{click:"more"}},more:function(b){var e=this;e.model.get("PostPublished");e.model.get("PostPublished").xfilter(e.xfilter).limit(e.limit).offset(e._views.length).sync().done(function(){var d=
e.model.get("PostPublished").total;e._views.length>=d&&m(b.target).hide()})},setIdInterval:function(b){this.idInterval=setInterval(b,this.timeInterval);return this},pause:function(){clearInterval(this.idInterval);return this},sync:function(){var b=this;this.auto().pause().setIdInterval(function(){b.auto()})},auto:function(){this.model.xfilter().sync({force:!0});return this},ensureStatus:function(){if(this.model.get("ClosedOn")){var b=new Date(this.model.get("ClosedOn"));this.pause();this.model.get("PostPublished").pause();
this.el.find("#liveblog-status").html(q("The liveblog coverage was stopped ")+b.format(q("mm/dd/yyyy HH:MM:ss")))}},gotoHash:function(){if(0<location.hash.length){var b=location.hash;location.hash="";location.hash=b}},init:function(){var b=this;b._views=[];b.rendered=!1;"string"===m.type(b.url)&&(b.model=new Blog(b.url.replace("my/","")));b.xfilter="PublishedOn, DeletedOn, Order, Id, CId, Content, CreatedOn, Type, AuthorName, Author.Source.Name, Author.Source.Id, IsModified, AuthorPerson.EMail, AuthorPerson.FirstName, AuthorPerson.LastName, AuthorPerson.Id, Meta";
b.model.on("read",function(){b.rendered||b.model.get("PostPublished").on("read readauto",b.render,b).on("addings addingsauto",b.addAll,b).on("addingsauto",b.updateTotal,b).on("updates updatesauto",b.updateStatus,b).on("beforeUpdate",b.updateingStatus,b).limit(b.limit).offset(b.offset).xfilter(b.xfilter).auto();b.rendered=!0}).on("update",function(){b.ensureStatus();b.renderBlog()});b.sync()},removeOne:function(b){b=this._views.indexOf(b);this.model.get("PostPublished").total--;this._views.splice(b,
1);return this},reorderOne:function(b){this._views.sort(function(b,d){return b.order-d.order});pos=this._views.indexOf(b);0===pos?b.el.insertAfter(this._views[1].el):b.el.insertBefore(this._views[0<pos?pos-1:1].el)},addOne:function(b){var d=new r({model:b,_parent:this}),m=this._views.length;b.postview=d;d.order=parseFloat(b.get("Order"));if(m){var q,l;for(p=0;p<m;p++)if(d.order>this._views[p].order)q=this._views[p],nextIndex=p;else if(d.order<this._views[p].order){l=this._views[p];prevIndex=p;break}l?
(d.el.insertAfter(l.el),this._views.splice(prevIndex,0,d)):q&&(d.el.insertBefore(q.el),this._views.splice(nextIndex+1,0,d))}else this.el.find("#liveblog-post-list").prepend(d.el),this._views=[d];return d},updateTotal:function(b,d){for(var m=d.length;m--;)this.model.get("PostPublished").total++},addAll:function(b,d){for(var m=d.length;m--;)this.addOne(d[m])},updateingStatus:function(){this.el.find("#liveblog-status").html(q("updating..."))},updateStatus:function(){var b=new Date;this.el.find("#liveblog-status").fadeOut(function(){m(this).text(q("updated on ")+
b.format(q("HH:MM:ss"))).fadeIn()})},renderBlog:function(){},loadTrace:function(){countLoaded>=totalLoad&&(this.gotoHash(),clearInterval(iidLoadTrace))},render:function(){var b=this.model.get("PostPublished").total;this.el.html('<article><h2></h2><p></p></article><div class="live-blog"><p class="update-time" id="liveblog-status"></p><div id="liveblog-posts"><ol id="liveblog-post-list" class="liveblog-post-list"></ol></div><div><a id="liveblog-more" href="javascript:void(0)">'+q("More")+"</a></div>");
this.limit>=b&&m("#liveblog-more",this.el).hide();this.renderBlog();this.ensureStatus();data=this.model.get("PostPublished")._list;totalLoad=b=data.length;var d=this,n;iidLoadTrace=setInterval(function(){d.loadTrace()},900);this.views=[];for(this.renderedTotal=b;b--;)data[b].on("rendered",this.renderedOn,this),n=this.addOne(data[b]),this.views.push(n)},renderedOn:function(){this.renderedTotal--;this.renderedTotal||(this.closeAllButFirstWrapup(),this.addClassToHashItem())},closeAllButFirstWrapup:function(b){b=
this.views;b.reverse();for(var d=0;d<b.length;d++)m(b[d].el).hasClass("wrapup")&&b[d]._toggleWrap(m(b[d].el))},addClassToHashItem:function(){var b=window.location.hash.split("#");1<b.length&&m('a[name="'+b[1]+'"]').addClass("hash-open")}});window.livedesk.TimelineView=d;window.livedesk.callback()};window.livedesk.init();
