window.livedesk._=function(l){return window.livedesk.i18n&&void 0!==window.livedesk.i18n[l]?window.livedesk.i18n[l]:l};
window.livedesk.loadGizmo=function(l){var s=this;(function(c){function p(a,h){var d=(a&65535)+(h&65535);return(a>>16)+(h>>16)+(d>>16)<<16|d&65535}function q(a,h,d,b,c,n){a=p(p(h,a),p(b,n));return p(a<<c|a>>>32-c,d)}function b(a,h,d,b,c,n,e){return q(h&d|~h&b,a,h,c,n,e)}function n(a,h,d,b,c,n,e){return q(h&b|d&~b,a,h,c,n,e)}function e(a,h,d,b,c,n,e){return q(d^(h|~b),a,h,c,n,e)}function t(a,h){a[h>>5]|=128<<h%32;a[(h+64>>>9<<4)+14]=h;var d,c,m,l,t,g=1732584193,f=-271733879,j=-1732584194,k=271733878;
for(d=0;d<a.length;d+=16)c=g,m=f,l=j,t=k,g=b(g,f,j,k,a[d],7,-680876936),k=b(k,g,f,j,a[d+1],12,-389564586),j=b(j,k,g,f,a[d+2],17,606105819),f=b(f,j,k,g,a[d+3],22,-1044525330),g=b(g,f,j,k,a[d+4],7,-176418897),k=b(k,g,f,j,a[d+5],12,1200080426),j=b(j,k,g,f,a[d+6],17,-1473231341),f=b(f,j,k,g,a[d+7],22,-45705983),g=b(g,f,j,k,a[d+8],7,1770035416),k=b(k,g,f,j,a[d+9],12,-1958414417),j=b(j,k,g,f,a[d+10],17,-42063),f=b(f,j,k,g,a[d+11],22,-1990404162),g=b(g,f,j,k,a[d+12],7,1804603682),k=b(k,g,f,j,a[d+13],12,
-40341101),j=b(j,k,g,f,a[d+14],17,-1502002290),f=b(f,j,k,g,a[d+15],22,1236535329),g=n(g,f,j,k,a[d+1],5,-165796510),k=n(k,g,f,j,a[d+6],9,-1069501632),j=n(j,k,g,f,a[d+11],14,643717713),f=n(f,j,k,g,a[d],20,-373897302),g=n(g,f,j,k,a[d+5],5,-701558691),k=n(k,g,f,j,a[d+10],9,38016083),j=n(j,k,g,f,a[d+15],14,-660478335),f=n(f,j,k,g,a[d+4],20,-405537848),g=n(g,f,j,k,a[d+9],5,568446438),k=n(k,g,f,j,a[d+14],9,-1019803690),j=n(j,k,g,f,a[d+3],14,-187363961),f=n(f,j,k,g,a[d+8],20,1163531501),g=n(g,f,j,k,a[d+13],
5,-1444681467),k=n(k,g,f,j,a[d+2],9,-51403784),j=n(j,k,g,f,a[d+7],14,1735328473),f=n(f,j,k,g,a[d+12],20,-1926607734),g=q(f^j^k,g,f,a[d+5],4,-378558),k=q(g^f^j,k,g,a[d+8],11,-2022574463),j=q(k^g^f,j,k,a[d+11],16,1839030562),f=q(j^k^g,f,j,a[d+14],23,-35309556),g=q(f^j^k,g,f,a[d+1],4,-1530992060),k=q(g^f^j,k,g,a[d+4],11,1272893353),j=q(k^g^f,j,k,a[d+7],16,-155497632),f=q(j^k^g,f,j,a[d+10],23,-1094730640),g=q(f^j^k,g,f,a[d+13],4,681279174),k=q(g^f^j,k,g,a[d],11,-358537222),j=q(k^g^f,j,k,a[d+3],16,-722521979),
f=q(j^k^g,f,j,a[d+6],23,76029189),g=q(f^j^k,g,f,a[d+9],4,-640364487),k=q(g^f^j,k,g,a[d+12],11,-421815835),j=q(k^g^f,j,k,a[d+15],16,530742520),f=q(j^k^g,f,j,a[d+2],23,-995338651),g=e(g,f,j,k,a[d],6,-198630844),k=e(k,g,f,j,a[d+7],10,1126891415),j=e(j,k,g,f,a[d+14],15,-1416354905),f=e(f,j,k,g,a[d+5],21,-57434055),g=e(g,f,j,k,a[d+12],6,1700485571),k=e(k,g,f,j,a[d+3],10,-1894986606),j=e(j,k,g,f,a[d+10],15,-1051523),f=e(f,j,k,g,a[d+1],21,-2054922799),g=e(g,f,j,k,a[d+8],6,1873313359),k=e(k,g,f,j,a[d+15],
10,-30611744),j=e(j,k,g,f,a[d+6],15,-1560198380),f=e(f,j,k,g,a[d+13],21,1309151649),g=e(g,f,j,k,a[d+4],6,-145523070),k=e(k,g,f,j,a[d+11],10,-1120210379),j=e(j,k,g,f,a[d+2],15,718787259),f=e(f,j,k,g,a[d+9],21,-343485551),g=p(g,c),f=p(f,m),j=p(j,l),k=p(k,t);return[g,f,j,k]}function m(a){var h,d="";for(h=0;h<32*a.length;h+=8)d+=String.fromCharCode(a[h>>5]>>>h%32&255);return d}function G(a){var h,d=[];d[(a.length>>2)-1]=void 0;for(h=0;h<d.length;h+=1)d[h]=0;for(h=0;h<8*a.length;h+=8)d[h>>5]|=(a.charCodeAt(h/
8)&255)<<h%32;return d}function r(a,h){var d,b=G(a),c=[],n=[];c[15]=n[15]=void 0;16<b.length&&(b=t(b,8*a.length));for(d=0;16>d;d+=1)c[d]=b[d]^909522486,n[d]=b[d]^1549556828;d=t(c.concat(G(h)),512+8*h.length);return m(t(n.concat(d),640))}function J(a){var h="",d,b;for(b=0;b<a.length;b+=1)d=a.charCodeAt(b),h+="0123456789abcdef".charAt(d>>>4&15)+"0123456789abcdef".charAt(d&15);return h}function B(a){a=unescape(encodeURIComponent(a));return m(t(G(a),8*a.length))}function u(a,h){var d;if("undefined"==
typeof a||"undefined"==typeof h)return!0;for(d in h)if("undefined"==typeof a[d])return!0;for(d in a)if("undefined"==typeof h[d])return!0;for(d in h)if(h[d])switch(typeof h[d]){case "object":if(u(h[d],a[d]))return!0;break;case "function":if("undefined"==typeof a[d]||h[d].toString()!=a[d].toString())return!0;break;default:if(h[d]!=a[d])return!0}else if(a[d])return!0;return!1}str=function(a){this.init(a)};str.format=function(a){var h=arguments,d=1;2==h.length&&"object"==typeof h[1]&&(h=h[1]);return a.replace(/%?%(?:\(([^\)]+)\))?([disr])/g,
function(a,b,c){if(a[0]==a[1])return a.substring(1);b=h[b||d++];return"undefined"===typeof b?a:"i"==c||"d"==c?+b:b})};str.prototype={init:function(a){this.str=a},format:function(){return str.format(this.str)},toString:function(){return this.str}};c.md5=function(a,h,d){return!h?d?B(a):J(B(a)):d?r(unescape(encodeURIComponent(h)),unescape(encodeURIComponent(a))):J(r(unescape(encodeURIComponent(h)),unescape(encodeURIComponent(a))))};var z={url:"//gravatar.com/avatar/%(md5)s?r=%(rate)s&s=%(size)s&d=%(default)s&%(forcedefault)s",
defaults:{rate:"pg",size:48,"default":encodeURIComponent("images/avatar_default_collaborator.png"),forcedefault:"",key:"Avatar",needle:"Person.EMail"},parse:function(a,h){if(a){h||(h=this.defaults.needle);var d=this,b=h.split("."),n=b[0],e=b[1];c.each(a,function(a,b){a===n&&(void 0!==e&&c.isDefined(b[e]))&&(this[d.defaults.key]=d.get(b[e]));(c.isObject(b)||c.isArray(b))&&d.parse(b,h)});return a}},get:function(a){return"string"!==c.type(a)?a:str.format(this.url,c.extend({},this.defaults,{md5:c.md5(c.trim(a.toLowerCase()))}))}};
c.avatar=z;var w,Q=/d{1,4}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|[LloSZ]|"[^"]*"|'[^']*'/g,R=/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g,S=/[^-+\dA-Z]/g,y=function(a,h){a=String(a);for(h=h||2;a.length<h;)a="0"+a;return a};w=function(a,h,d){1==arguments.length&&("[object String]"==Object.prototype.toString.call(a)&&!/\d/.test(a))&&(h=a,a=void 0);a=a?new Date(a):new Date;if(isNaN(a))throw SyntaxError("invalid date");
h=String(w.masks[h]||h||w.masks["default"]);"UTC:"==h.slice(0,4)&&(h=h.slice(4),d=!0);var b=d?"getUTC":"get",c=a[b+"Date"](),n=a[b+"Day"](),e=a[b+"Month"](),g=a[b+"FullYear"](),f=a[b+"Hours"](),j=a[b+"Minutes"](),k=a[b+"Seconds"](),b=a[b+"Milliseconds"](),m=d?0:a.getTimezoneOffset(),l={d:c,dd:y(c),ddd:w.i18n.dayNames[n],dddd:w.i18n.dayNames[n+7],m:e+1,mm:y(e+1),mmm:w.i18n.monthNames[e],mmmm:w.i18n.monthNames[e+12],yy:String(g).slice(2),yyyy:g,h:f%12||12,hh:y(f%12||12),H:f,HH:y(f),M:j,MM:y(j),s:k,
ss:y(k),l:y(b,3),L:y(99<b?Math.round(b/10):b),t:12>f?"a":"p",tt:12>f?"am":"pm",T:12>f?"A":"P",TT:12>f?"AM":"PM",Z:d?"UTC":(String(a).match(R)||[""]).pop().replace(S,""),o:(0<m?"-":"+")+y(100*Math.floor(Math.abs(m)/60)+Math.abs(m)%60,4),S:["th","st","nd","rd"][3<c%10?0:(10!=c%100-c%10)*c%10]};return h.replace(Q,function(a){return a in l?l[a]:a.slice(1,a.length-1)})};w.masks={"default":"ddd mmm dd yyyy HH:MM:ss",shortDate:"m/d/yy",mediumDate:"mmm d, yyyy",longDate:"mmmm d, yyyy",fullDate:"dddd, mmmm d, yyyy",
shortTime:"h:MM TT",mediumTime:"h:MM:ss TT",longTime:"h:MM:ss TT Z",isoDate:"yyyy-mm-dd",isoTime:"HH:MM:ss",isoDateTime:"yyyy-mm-dd'T'HH:MM:ss",isoUtcDateTime:"UTC:yyyy-mm-dd'T'HH:MM:ss'Z'"};w.i18n={dayNames:"Sun Mon Tue Wed Thu Fri Sat Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),monthNames:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec January February March April May June July August September October November December".split(" ")};window.livedesk.i18n&&void 0!==window.livedesk.i18n.day_names&&
(w.i18n.dayNames=window.livedesk.i18n.day_names);window.livedesk.i18n&&void 0!==window.livedesk.i18n.month_names&&(w.i18n.monthNames=window.livedesk.i18n.month_names);Date.prototype.format=function(a,h){return w(this,a,h)};Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});Function.prototype.bind||(Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");
var h=Array.prototype.slice.call(arguments,1),d=this,b=function(){},c=function(){return d.apply(this instanceof b?this:a,h.concat(Array.prototype.slice.call(arguments)))};b.prototype=this.prototype;c.prototype=new b;return c});String.prototype.trim||(String.prototype.trim=function(){for(var a=this.replace(/^\s\s*/,""),b=/\s/,d=a.length;b.test(a.charAt(--d)););return a.slice(0,d+1)});var H=!1;this.Class=function(){};Class.extend=function(a,b){function d(){if(!H&&(this._constructor||this._construct))try{return(this._construct||
this._constructor).apply(this,arguments)}catch(a){}}H=!0;var c=new this;H=!1;for(var n in a)c[n]=a[n];d.prototype=c;d.prototype.constructor=d;d.extend=arguments.callee;return d};var K=function(){},v=function(){},L=function(){this.items={}},x=function(){},M=Class.extend({_construct:function(a){this.data=!this.data?{root:""}:this.data;switch(c.type(a)){case "string":this.data.url=a;break;case "array":this.data.url=a[0];void 0!==a[1]&&(this.data.xfilter=url[0]);break;case "object":this.data.url=a.url,
void 0!==a.xfilter&&(this.data.xfilter=a.xfilter)}return this},xfilter:function(){this.data.xfilter=1<arguments.length?c.makeArray(arguments).join(","):c.isArray(arguments[0])?arguments[0].join(","):arguments[0];return this},root:function(a){this.data.root=a;return this},get:function(){return this.data.root+this.data.url},order:function(a,b){this.data.order=b+"="+a;return this},filter:function(a,b){this.data.filter=a+"="+b;return this},decorate:function(a){this.data.url=a.replace(/(%s)/g,this.data.url)},
options:function(){var a={};this.data.xfilter&&(a.headers={"X-Filter":this.data.xfilter});return a}}),A={request:function(a){var b=this,d=function(d,n,e){c.support.cors=!0;a instanceof M?(n=c.extend(!0,{},n,b.options,e,{data:d},a.options()),d=c.ajax(b.href(a.get()),n)):(n=c.extend(!0,{},n,b.options,e,{data:d}),d=c.ajax(b.href(a),n));b.reset();n.fail&&d.fail(n.fail);n.done&&d.done(n.done);n.always&&d.always(n.always);return d};return{read:function(a){return d({},b.readOptions,a)},update:function(a,
c){return d(a,b.updateOptions,c)},insert:function(a,c){return d(a,b.insertOptions,c)},remove:function(a){return d({},b.removeOptions,a)}}},href:function(a){return a},reset:c.noop,options:{},readOptions:{dataType:"json",type:"get",headers:{Accept:"text/json"}},updateOptions:{type:"post",headers:{"X-HTTP-Method-Override":"PUT"}},insertOptions:{dataType:"json",type:"post"},removeOptions:{type:"get",headers:{"X-HTTP-Method-Override":"DELETE"}}},T=0;v.prototype={_changed:!1,_new:!1,defaults:{},data:{},
_construct:function(a,b){this._clientId=T++;this.data={};this.parseHash(a);this._new=!0;var d=this.pushUnique?this.pushUnique():this;d._forDelete=!1;d.clearChangeset();d._clientHash=null;b&&"object"==typeof b&&c.extend(d,b);"object"==typeof a&&(d._parse(a),d._setExpiration());c.isEmptyObject(d.changeset)||d.triggerHandler("update",d.changeset).clearChangeset();return d},syncAdapter:A,feed:function(a,b,d){var a={},d=d?d:this.data,c;for(c in d)a[c]=d[c]instanceof v?b?d[c].feed(b):d[c].relationHash()||
d[c].hash():d[c];return a},sync:function(a,b){var d=this,n=c.Deferred(),e=function(){return d.syncAdapter.request.apply(d.syncAdapter,arguments)};this.hash();d.triggerHandler("sync");if(this._forDelete)return e(a||this.href).remove().done(function(){d._remove()});if(this._clientHash)return e(a||this.href).insert(this.feed()).done(function(a){d._changed=!1;d._parse(a);d._uniq&&d._uniq.replace(d._clientHash,d.hash(),d);d._clientHash=null;d.triggerHandler("insert").Class.triggerHandler("insert",d)});
this._changed?c.isEmptyObject(this.changeset)||(n=this.href&&e(this.href).update(b?this.feed():this.feed("json",!1,this.changeset)).done(function(){d.triggerHandler("update",d.changeset).clearChangeset()})):(!a||!a.force)&&this.exTime&&this.exTime>new Date?d.isDeleted()||d.triggerHandler("update"):n=this.href&&e(this.href).read(a).done(function(a){d._parse(a);d.isDeleted()?d._remove():c.isEmptyObject(d.changeset)?d.clearChangeset().triggerHandler("read"):d.triggerHandler("update",d.changeset).clearChangeset()});
this._setExpiration();return n},_setExpiration:function(){this.exTime=new Date;this.exTime.setSeconds(this.exTime.getSeconds()+5)},_remove:function(){this.triggerHandler("delete");this._uniq&&this._uniq.remove(this.hash())},remove:function(){this._forDelete=!0;return this},isDeleted:function(){return this._forDelete},modelDataBuild:function(a){return a},parse:function(a){return a},_parse:function(a){a=a instanceof v?a.data:this.parse(a);if(!a._parsed){for(var b in a){if(this.defaults[b])switch(!0){case "function"===
typeof this.defaults[b]&&void 0===this.data[b]:var d=this.modelDataBuild(new this.defaults[b](a[b]));!this._new&&(d!=this.data[b]&&!(d instanceof x))&&(this.changeset[b]=d);this.data[b]=d;!a[b].href&&this.data[b].relationHash&&this.data[b].relationHash(a[b]);continue;case c.isArray(this.defaults[b]):this.data[b]=this.modelDataBuild(new x(this.defaults[b][0],a[b].href));delete this.data[b];continue;case this.defaults[b]instanceof x:case this.defaults[b]instanceof v:this.data[b]=this.defaults[b];continue}else this._new||
("object"===c.type(a[b])?u(this.data[b],a[b])&&(this.changeset[b]=a[b]):this.data[b]!=a[b]&&(this.changeset[b]=a[b]));"object"===c.type(a[b])&&"object"===c.type(this.data[b])?c.extend(!0,this.data[b],a[b]):this.data[b]=a[b]}this._new=!1;a._parsed=!0}},parseHash:function(a){if(a instanceof v)return this;"string"==typeof a?this.href=a:a&&void 0!==a.href?(this.href=a.href,delete a.href):a&&(void 0!==a.id&&void 0!==this.url)&&(this.href=this.url+a.id);return this},isChanged:function(){return!c.isEmptyObject(this.changeset)},
clearChangeset:function(){this._changed=!1;this.changeset={};return this},get:function(a){return this.data[a]},set:function(a,b,d){var n={};"string"===c.type(a)?n[a]=b:(n=a,d=b);d=c.extend({},{silent:!1},d);this.clearChangeset()._parse(n);this._changed=!0;c.isEmptyObject(this.changeset)||d.silent||this.triggerHandler("set",this.changeset);return this},_getClientHash:function(){this._clientHash||(this._clientHash="mcid-"+String(this._clientId));return this._clientHash},hash:function(){!this.href&&
this.data.href&&(this.href=this.data.href);return this.data.href||this.href||this._getClientHash()},relationHash:function(a){a&&(this.data.Id=a);return this.data.Id},off:function(a,b){c(this).off(a,b);return this},on:function(a,b,d){if(void 0===d)c(this).off(a,b),c(this).on(a,b);else c(this).on(a,function(){b.apply(d,arguments)});return this},trigger:function(a,b){c(this).trigger(a,b);return this},triggerHandler:function(a,b){c(this).triggerHandler(a,b);return this}};L.prototype={items:{},garbageTime:1500,
refresh:function(a){a._exTime||(a._exTime=new Date);a._exTime.setTime(a._exTime.getTime()+this.garbageTime)},set:function(a,b){var d=this;c(b).on("sync get get-prop set-prop",function(){d.refresh(this)});d.refresh(b);this.items[a]||(this.items[a]=b);return this.items[a]},replace:function(a,b,d){delete this.items[a];return this.set(b,d)},garbage:function(){for(var a in this.items)this.items[a]._exTime&&this.items[a]._exTime<new Date&&(c(this.items[a]).triggerHandler("garbage"),delete this.items[a])},
remove:function(a){delete this.items[a]}};var C=v.options={},N,O;v.extend=N=function(a,b){var d;d=Class.extend.call(this,a);d.extend=N;d.prototype.Class=d;d.on=function(a,b,h){c(d).on(a,function(){b.apply(h,arguments)});return d};d.off=function(a,b){c(d).off(a,b);return d};d.triggerHandler=function(a,b){c(d).triggerHandler(a,b)};b&&b.register&&(K[b.register]=d,delete b.register);d.prototype.options=c.extend({},b);return d};x.prototype={_list:[],getList:function(){return this._list},count:function(){return this._list.length},
_construct:function(){this.model||(this.model=v);this._list=[];this.desynced=!0;var a=buildOptions=function(){void 0},b;for(b in arguments)switch(c.type(arguments[b])){case "function":this.model=arguments[b];break;case "string":this.href=arguments[b];break;case "array":a=function(a){return function(){this._list=this._parse(a)}}(arguments[b]);break;case "object":buildOptions=function(a){return function(){this.options=a;a.href&&(this.href=a.href)}}(arguments[b])}buildOptions.call(this);a.call(this);
C=c.extend({},{init:!0},this.options);C.init&&this.init.apply(this,arguments)},init:function(){},get:function(a){var b=c.Deferred(),d=this;searchKey=function(){for(var c=0;c<d._list.length;c++)if(a==d._list[c].hash()||a==d._list[c].relationHash())return b.resolve(d._list[c]);b.reject()};this.desynced&&this.sync().done(function(){b.resolve(searchKey())})?b:searchKey();return b},remove:function(a){for(var b in this._list)if(a==this._list[b].hash()||a==this._list[b].relationHash()){Array.prototype.splice.call(this._list,
b,1);break}return this},syncAdapter:A,setHref:function(a){this.href=a;return this},each:function(a){c.each(this._list,a)},forwardEach:function(a,b){this._list.forEach(a,b)},reverseEach:function(a,b){for(var d=this._list.length;0<d;++d)a.call(b||this,this[d],d,this)},feed:function(a,b){var d=[],c;for(c in this._list)d[c]=this._list[c].feed(a,b);return d},sync:function(a){var b=this;return this.href&&this.syncAdapter.request.call(this.syncAdapter,this.href).read(a).done(function(a){for(var a=b._parse(a),
c=[],n=b._list.length,e=0;e<a.list.length;e++){for(var m=!1,g=0;g<n;g++)if(a.list[e].hash()==b._list[g].hash()){m=a.list[e];break}if(m)if(b._list[g]._parse(m.data),m.isDeleted())m._remove();else if(m.isChanged())c.push(a.list[e]);else m.on("delete",function(){b.remove(this.hash())}).on("garbage",function(){this.desynced=!0});else b._list.push(a.list[e]),c.push(a.list[e])}b.desynced=!1;0===n?b.triggerHandler("read"):b.triggerHandler("update",[c])})},modelDataBuild:function(a){return a},parse:function(a){return a},
_parse:function(a){if(a._parsed)return a._parsed;var a=this.parse(a),b,d=b=a;if(!Array.isArray(b))for(n in b)if(c.isArray(b[n])){d=b[n];break}b=d;list=[];for(var n in b)b.hasOwnProperty(n)&&list.push(this.modelDataBuild(new this.model(b[n])));a._parsed={list:list,total:a.total};return a._parsed},insert:function(a){this.desynced=!1;a instanceof v||(a=this.modelDataBuild(new this.model(a)));this._list.push(a);a.hash();return a.sync(this.href)},off:function(a,b){c(this).off(a,b);return this},on:function(a,
b,d){if(void 0===d)c(this).off(a,b),c(this).on(a,b);else c(this).on(a,function(){b.apply(d,arguments)});return this},trigger:function(a,b){c(this).trigger(a,b);return this},triggerHandler:function(a,b){c(this).triggerHandler(a,b);return this}};x.extend=O=function(a){a=Class.extend.call(this,a);a.extend=O;C&&C.register&&(x[C.register]=a);return a};var U=0,z=Class.extend({getProperty:function(a){return!this[a]?null:"function"===typeof this[a]?this[a]():this[a]}}).extend({tagName:"div",attributes:{className:"",
id:""},namespace:"view",_constructor:function(a,b){c.extend(this,a);this._clientId=U++;b=c.extend({},{init:!0,events:!0,ensure:!0},b);b.ensure&&this._ensureElement();b.init&&this.init.apply(this,arguments);b.events&&this.resetEvents()},_ensureElement:function(){var a=this.attributes.className,b=this.attributes.id,d="";c(this.el).length?this.el=c(this.el):("string"===c.type(this.el)&&("."==this.el[0]&&(a+=this.el.substr(0,1)),"#"==this.el[0]&&(b=this.el.substr(0,1))),d="<"+this.tagName,""!==a&&(d=
d+' class="'+a+'"'),""!==b&&(d=d+' id="'+b+'"'),d=d+"></"+this.tagName+">",this.el=c(d))},init:function(){return this},resetEvents:function(){this.undelegateEvents();this.delegateEvents()},delegateEvents:function(a){if(a||(a=this.getProperty("events")))for(var b in a){var d=a[b],n;for(n in d){var e=d[n];if("string"===typeof e&&c.isFunction(this[e]))c(this.el).on(this.getEvent(n),b,this[e].bind(this))}}},undelegateEvents:function(){c(this.el).off(this.getNamespace());return this},getEvent:function(a){return a+
this.getNamespace()},getNamespace:function(){return"."+this.getProperty("namespace")},render:function(){this.delegateEvents();return this},remove:function(){c(this.el).remove();this.destroy();return this},destroy:function(){this.model&&this.model.trigger("destroy");this.collection&&this.collection.trigger("destroy");return this},checkElement:function(){return void 0===this.el?!1:void 0!==this.el.selector&&""!=this.el.selector?1===c(this.el.selector).length:c(this.el).is(":visible")},setElement:function(a){this.undelegateEvents();
var a=c(a),b=this.el.data();this.el.replaceWith(a);this.el=a;this.el.data(b);this.delegateEvents();return this},resetElement:function(a){this.el=c(a);this._ensureElement();this.delegateEvents()}}),P=v,I=x,A=c.extend({},A,{reset:function(){try{delete this.options.headers["X-Filter"],delete this.options.data["CId.since"],delete this.options.data.offset,delete this.options.data.limit}catch(a){}}}),V=function(){var a=this;AuthApp.success=function(){a.options.headers.Authorization=localStorage.getItem("superdesk.login.session")};
AuthApp.require.apply(a,arguments)},D=c.extend({},A,{options:{headers:{Authorization:localStorage.getItem("superdesk.login.session")},fail:function(a){401==a.status&&V.apply(D,arguments);404==a.status&&ErrorApp.require.apply(this,arguments)}},href:function(a){return-1===a.indexOf("my/")?a.replace("resources/","resources/my/"):a}}),E=function(){this.syncAdapter.options.headers||(this.syncAdapter.options.headers={});this._xfilter=1<arguments.length?c.makeArray(arguments).join(","):c.isArray(arguments[0])?
arguments[0].join(","):arguments[0];this.syncAdapter.options.headers["X-Filter"]=this._xfilter;this.syncAdapter.options.headers["X-Format-DateTime"]="M/dd/yyyy HH:mm:ss";return this},F=function(a){a?c.extend(!0,this.syncAdapter.options,{data:{"CId.since":a}}):delete this.syncAdapter.options.data["CId.since"];return this},v=P.extend({isDeleted:function(){return this._forDelete||this.data.DeletedOn},syncAdapter:A,xfilter:E,since:F}),W=v.extend({syncAdapter:D,xfilter:E,since:F}),x=I.extend({xfilter:E,
since:F,asc:function(a){c.extend(!0,this.syncAdapter.options,{data:{asc:a}});return this},desc:function(a){c.extend(!0,this.syncAdapter.options,{data:{desc:a}});return this},limit:function(a){c.extend(!0,this.syncAdapter.options,{data:{limit:a}});return this},offset:function(a){c.extend(!0,this.syncAdapter.options,{data:{offset:a}});return this},syncAdapter:A}),I=x.extend({xfilter:E,since:F,syncAdapter:D});v.extend=function(){var a=P.extend.apply(this,arguments),b=new L;c.extend(a.prototype,{_uniq:b,
pushUnique:function(){return b.set(this.hash(),this)}},arguments[0]);return a};c.gizmo={Model:v,AuthModel:W,Collection:x,AuthCollection:I,Sync:A,AuthSync:D,View:z,Url:M,Register:K};s.preLoad(l)})(jQuery)};function isOnly(l,s){"string"===$.type(s)&&(s=[s]);var c=0,p=s.length;for(i in l){if(-1===$.inArray(i,s))return!1;c++;if(c>p)return!1}return c===p}var root=this;
window.livedesk.loadXDRequest=function(l){var s=l;root.XDomainRequest&&s.ajaxTransport("+*",function(c){if(c.crossDomain&&c.async){c.timeout&&(c.xdrTimeout=c.timeout,delete c.timeout);var l;return{send:function(q,b){function n(c,n,e,r){l.onload=l.onerror=l.ontimeout=s.noop;l=void 0;b(c,n,e,r)}l=new XDomainRequest;if(c.dataType){var e="";for(i in c.headers)e+=i+"="+encodeURIComponent(c.headers[i])+"&";e=e.replace(/(\s+)?.$/,"");c.url=c.url+(-1===c.url.indexOf("?")?"?":"&")+e}l.open(c.type,c.url);l.onload=
function(){n(200,"OK",{text:l.responseText},"Content-Type: "+l.contentType)};l.onerror=function(){n(404,"Not Found")};c.xdrTimeout&&(l.ontimeout=function(){n(0,"timeout")},l.timeout=c.xdrTimeout);l.send(c.hasContent&&c.data||null)},abort:function(){l&&(l.onerror=s.noop(),l.abort())}}}})};
window.livedesk.init=function(){window.livedesk.location=window.location.href.split("#")[0];var l=this,s=!1,c=!1;contentPath=void 0===l.contentPath?"":l.contentPath;"undefined"==typeof jQuery?s=!0:1.7>parseFloat($().jquery)&&(c=s=!0);s?l.loadScript("//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js",function(){l.loadXDRequest(jQuery);"undefined"==typeof $.gizmo?l.loadGizmo(c):l.preLoad(c)}):(l.loadXDRequest(jQuery),"undefined"==typeof $.gizmo?l.loadGizmo(c):l.preLoad(c))};
window.livedesk.loadScript=function(l,s){var c=document.createElement("script");c.type="text/javascript";c.readyState?c.onreadystatechange=function(){if("loaded"==c.readyState||"complete"==c.readyState)c.onreadystatechange=null,s()}:c.onload=function(){s()};c.src=l;document.getElementsByTagName("head")[0].appendChild(c)};window.livedesk.preLoad=function(l){l?(l=$.noConflict(!0),this.startLoading(l,window.livedesk._)):this.startLoading(jQuery,window.livedesk._)};
window.livedesk.startLoading=function(l,s){var c=l.gizmo.Model.extend({}),c=l.gizmo.Model.extend({defaults:{Creator:c},services:{flickr:!0,google:!0,twitter:!0,facebook:!0,youtube:!0},getClass:function(){switch(this.get("Type").Key){case "wrapup":return"wrapup";case "quote":return"quotation";case "advertisement":return"advertisement";default:return this.isService()?"service":"tw"}},isService:function(){return this.get("AuthorName")in this.services},isQuote:function(){return"quotation"==this.getClass()},
twitter:{link:{anchor:function(b){return b.replace(/[A-Za-z]+:\/\/[A-Za-z0-9-_]+\.[A-Za-z0-9-_:%&\?\/.=]+/g,function(b){b=b.link(b);return b=b.replace('href="','target="_blank" href="')})},user:function(b){return b.replace(/[@]+[A-Za-z0-9-_]+/g,function(b){var c=b.replace("@",""),b=b.link("http://twitter.com/"+c);return b=b.replace('href="','target="_blank" onclick="loadProfile(\''+c+'\');return(false);"  href="')})},tag:function(b){return b.replace(/[#]+[A-Za-z0-9-_]+/g,function(b){var c=b.replace(" #",
" %23"),b=b.link("http://summize.com/search?q="+c);return b=b.replace('href="','target="_blank" href="')})},all:function(b){b=this.anchor(b);b=this.user(b);return b=this.tag(b)}}}});Posts=l.gizmo.Collection.extend({timeInterval:1E4,idInterval:0,_latestCId:0,keep:!1,init:function(){var b=this;b.model.on("publish reorder",function(c,e){b.getMaximumNearCid(b._parse([e]))});this.on("read update",function(c,e){e||(e=b._list);b.getMaximumCid(b._parse(e))})},destroy:function(){this.stop()},setIdInterval:function(b){this.idInterval=
setInterval(b,this.timeInterval);return this},getMaximumNearCid:function(b){p=0;for(count=b.list.length;p<count;p++){var c=parseInt(b.list[p].get("CId"));!isNaN(c)&&(this._latestCId<c&&this._latestCId+1==c)&&(this._latestCId=c)}},getMaximumCid:function(b){p=0;for(count=b.list.length;p<count;p++){var c=parseInt(b.list[p].get("CId"));!isNaN(c)&&this._latestCId<c&&(this._latestCId=c)}},start:function(){var b={data:{"cId.since":this._latestCId},headers:{"X-Filter":this._xfilter,"X-Format-DateTime":"M/dd/yyyy HH:mm:ss"}};
0===this._latestCId&&delete b.data;if(!this.keep&&this.view&&!this.view.checkElement())this.stop();else return this.sync(b)},stop:function(){clearInterval(this.idInterval);return this},autosync:function(){var b=this;ret=this.stop().start();this.setIdInterval(function(){b.start()});return ret}}).extend({parse:function(b){void 0!==b.total&&(b.total=parseInt(b.total),b.offset=parseInt(b.offset),void 0===this.total?(this.delta=0,this.total=b.total):0===b.offset&&(this.delta+=b.total,this.total+=b.total),
delete b.total);return b.PostList?b.PostList:b},model:c});Blog=l.gizmo.Model.extend({defaults:{PostPublished:Posts}});var p=0,q;q=l.gizmo.View.extend({init:function(){var b=this;b.xfilter="PublishedOn, DeletedOn, Order, Id, CId, Content, CreatedOn, Type, AuthorName, Author.Source.Name, Author.Source.Id, IsModified, AuthorPerson.EMail, AuthorPerson.FirstName, AuthorPerson.LastName, AuthorPerson.Id, Meta";b.model.on("read update",function(c,e){var l=void 0;this.data._parsed&&(l=this.data._parsed,delete this.data._parsed);
isOnly(this.data,["CId","Order"])||isOnly(e,["CId","Order"])?b.model.xfilter(b.xfilter).sync({force:!0}):b.render(c,e);this.data._parsed=l}).on("delete",b.remove,b).xfilter(b.xfilter).sync()},remove:function(){this.tightkNots();this.el.remove();return this},tightkNots:function(){void 0!==this.next&&(this.next.prev=this.prev);void 0!==this.prev&&(this.prev.next=this.next)},itemTemplate:function(b,c,e,l){var m="",p=b.getClass(),r=b.get("AuthorName"),q="",B="";if(b.data.hasOwnProperty("Meta")){var u=
b.data.Meta;"string"==typeof u&&(u=JSON.parse(u));u.hasOwnProperty("annotation")&&("string"===typeof u.annotation?B='<div class="editable annotation">'+u.annotation+"</div>":null!==u.annotation[1]?(q='<div class="editable annotation">'+u.annotation[0]+"</div>",B='<div class="editable annotation">'+u.annotation[1]+"</div>"):B='<div class="editable annotation">'+u.annotation[0]+"</div>")}avatarString="";"true"!=s("no_avatar")&&(0<l.length&&"twitter"!=r)&&(avatarString='<figure><img src="'+l+'" ></figure>');
switch(p){case "tw":case "service":m=m+q+avatarString;m+='<div class="result-content">';"twitter"==r?(m+='<blockquote class="twitter-tweet"><p>'+c+"</p>&mdash; "+u.from_user_name+" (@"+u.from_user_name+') <a href="https://twitter.com/'+u.from_user+"/status/"+u.id_str+'" data-datetime="'+u.created_at+'"></a></blockquote>',window.livedesk.loadedTweeterScript||(window.livedesk.loadScript("//platform.twitter.com/widgets.js",function(){}),window.livedesk.loadedTweeterScript=!0)):"youtube"==r?(m+='<div class="result-text">'+
c+"</div>",m+='<p class="attributes"><i class="source-icon"></i> '+s("by")+" ",m+='<a class="author-name" href="http://youtube.com/'+u.uploader+'" target="_blank">'+u.uploader+"</a>"):"google"==r?(m+='<h3><a target="_blank" href="'+u.unescapedUrl+'">'+u.title+"</a></h3>",m+='<div class="result-text">'+c+"</div>",m+='<p class="attributes"><i class="source-icon"></i> '+s("by")+" "+b.get("AuthorName")):"flickr"==r?(m+='<div class="result-text">'+c+"</div>",m+='<p class="attributes"><i class="source-icon"></i> '+
s("by")+" "+b.get("AuthorName")):(m+='<div class="result-text">'+c+"</div>",m+='<p class="attributes"><i class="source-icon"></i> '+s("by")+" "+b.get("AuthorName"),m+="<time>"+e+"</time>");m+="</p>";m+="</div>";m+=B;break;case "quotation":var z,b=b.get("AuthorName"),e=c.split("<div><br><br></div>"),l=c.split("<br><br><br>");2==e.length?(c=e[0],z='<div class="quotation-author">'+e[1]+"</div>"):2==l.length&&(c=l[0],z='<div class="quotation-author">'+l[1]+"</div>");m+='<div class="result-content">';
m+='<div class="result-text">'+c+"</div>";m=z?m+z:m+('<div class="attributes">'+s("by")+" "+b+"</div>");m+="</div>";break;case "wrapup":m+='<span class="big-toggle"></span>';m+="<h3>"+c+"</h3>";break;case "advertisement":m+=c}return m},toggleWrap:function(b,c){"boolean"!=typeof c&&(c=!1);this._toggleWrap(l(b).closest("li").first(),c)},_toggleWrap:function(b,c){"boolean"!=typeof c&&(c=!1);if(b.hasClass("open")){var e=!0,t=window.location.hash;0<t.length&&!1==c&&b.nextUntil(".wrapup").each(function(){"#"+
l(this).find("a").attr("name")==t&&(e=!1)});e&&(b.removeClass("open").addClass("closed"),b.nextUntil(".wrapup").hide())}else b.removeClass("closed").addClass("open"),b.nextUntil(".wrapup").show()},togglePermalink:function(b){this._togglePermalink(l(b).next('input[data-type="permalink"]'))},_togglePermalink:function(b){"visible"==b.css("visibility")?b.css("visibility","hidden"):b.css("visibility","visible")},render:function(){countLoaded++;var b=this,c=parseFloat(b.model.get("Order")),e="";this.model.get("AuthorPerson")&&
this.model.get("AuthorPerson").EMail&&(e=l.avatar.get(b.model.get("AuthorPerson").EMail));if(!isNaN(b.order)&&c!=b.order){for(var t={prev:"insertBefore",next:"insertAfter"},m={prev:1,next:-1},p={prev:"next",next:"prev"},r=0<b.order-c?"next":"prev",q=b[r];q&&void 0!==q[r]&&q[r].order*m[r]<c*m[r];q=q[r]);q&&(m=q[r],void 0!==m&&(m[p[r]]=b),q[r]=b,b.tightkNots(),b[r]=m,b[p[r]]=q,b.el[t[r]](q.el))}b.order=c;t=b.model.get("Content");c="";"wrapup"==b.model.getClass()&&(c+="open ");b.model.isService()&&(c+=
b.model.get("AuthorName"),p=JSON.parse(b.model.get("Meta")),r=b.model.get("PublishedOn"),r=new Date(r),q=r.format("ddd mmm dd yyyy HH:MM:ss TT"),"flickr"==b.model.get("AuthorName")?(t=l("<span>"+t+"</span>"),t.find("img").attr("src",t.find("a").attr("href")),t=t.html()):"twitter"==b.model.get("AuthorName")?(e=p.profile_image_url,t=b.model.twitter.link.all(t)):"google"==b.model.get("AuthorName")&&p.tbUrl&&(t+='<p><a href="'+p.url+'"><img src="'+p.tbUrl+'" height="'+p.tbHeight+'" width="'+p.tbWidth+
'"></a></p>'));r=b.model.get("PublishedOn");r=new Date(r);q=r.format(s("ddd mmm dd yyyy HH:MM:ss TT"));"true"===s("show_current_date")&&(new Date).format("mm dd yyyy")==r.format("mm dd yyyy")&&(q=r.format(s("HH:MM:ss TT")));b.model.get("AuthorName");t=b.itemTemplate(b.model,t,q,e);p=b.model.get("Id");e=b._parent.model.get("Title");e=e.replace(/ /g,"-");e=p+"-"+encodeURI(e);e=p;p=b.model.getClass();r=window.livedesk.location+"#"+e;q="";"advertisement"!==p&&"wrapup"!==p&&(q='<a rel="bookmark" href="#'+
e+'">#</a><input type="text" value="'+r+'" style="visibility:hidden" data-type="permalink" />');e='<li class="'+c+p+'"><a name="'+e+'"></a>'+t+"&nbsp;"+q+"</li>";"undefined"!=typeof window.livedesk.productionServer&&"undefined"!=typeof window.livedesk.frontendServer&&(re=RegExp(window.livedesk.productionServer,"g"),e=e.replace(re,window.livedesk.frontendServer));b.setElement(e);b.model.triggerHandler("rendered");l(b.el).off("click.livedesk",".big-toggle").on("click.livedesk",".big-toggle",function(){b.toggleWrap(this,
!0)});l(b.el).off("click.livedesk",'a[rel="bookmark"]').on("click.livedesk",'a[rel="bookmark"]',function(){b.togglePermalink(this)});l(b.el).off("click.livedesk",'input[data-type="permalink"]').on("focus.livedesk click.livedesk",'input[data-type="permalink"]',function(){l(this).select()})}});countLoaded=iidLoadTrace=totalLoad=0;c=l.gizmo.View.extend({limit:5,offset:0,el:"#livedesk-root",timeInterval:1E4,idInterval:0,_latestCId:0,events:{"#liveblog-more":{click:"more"}},more:function(b){var c=this,
e=l(b.target).data("offset"),p=c.model.get("PostPublished").delta,e=e?e:1;c.model.get("PostPublished").xfilter(c.xfilter).limit(c.limit).offset(e*c.limit+p).sync().done(function(){c.model.get("PostPublished").delta=0;var m=c.model.get("PostPublished").total;(e+1)*c.limit+p>=m&&l(b.target).hide()});l(b.target).data("offset",e+1)},setIdInterval:function(b){this.idInterval=setInterval(b,this.timeInterval);return this},pause:function(){clearInterval(this.idInterval);return this},sync:function(){var b=
this;this.auto().pause().setIdInterval(function(){b.auto()})},auto:function(){this.model.xfilter().sync({force:!0});return this},ensureStatus:function(){if(this.model.get("ClosedOn")){var b=new Date(this.model.get("ClosedOn"));this.pause();this.model.get("PostPublished").pause();this.el.find("#liveblog-status").html(s("The liveblog coverage was stopped ")+b.format(s("mm/dd/yyyy HH:MM:ss")))}},gotoHash:function(){if(0<location.hash.length){var b=location.hash;location.hash="";location.hash=b}},init:function(){var b=
this;b._views=[];b.rendered=!1;"string"===l.type(b.url)&&(b.model=new Blog(b.url.replace("my/","")));b.xfilter="PublishedOn, DeletedOn, Order, Id, CId, Content, CreatedOn, Type, AuthorName, Author.Source.Name, Author.Source.Id, IsModified, AuthorPerson.EMail, AuthorPerson.FirstName, AuthorPerson.LastName, AuthorPerson.Id, Meta";b.model.on("read",function(){b.rendered||b.model.get("PostPublished").on("read",b.render,b).on("update",b.addAll,b).on("beforeUpdate",b.updateingStatus,b).limit(b.limit).offset(b.offset).xfilter(b.xfilter).autosync();
b.rendered=!0}).on("update",function(){b.ensureStatus();b.renderBlog()});b.sync()},addOne:function(b){var c=new q({model:b,_parent:this}),e=this._views.length;b.postview=c;c.order=parseFloat(b.get("Order"));if(e){var l,m;for(p=0;p<e;p++)if(c.order>this._views[p].order)l=this._views[p],nextIndex=p;else if(c.order<this._views[p].order){m=this._views[p];prevIndex=p;break}m?(c.el.insertAfter(m.el),m.next=c,c.prev=m,this._views.splice(prevIndex,0,c)):l&&(c.el.insertBefore(l.el),this._views.splice(nextIndex+
1,0,c));l&&(l.prev=c,c.next=l)}else this.el.find("#liveblog-post-list").prepend(c.el),this._views=[c];return c},addAll:function(b,c){for(var e=c.length;e--;)this.addOne(c[e]);this.updateStatus()},updateingStatus:function(){this.el.find("#liveblog-status").html(s("updating..."))},updateStatus:function(){var b=new Date;this.el.find("#liveblog-status").fadeOut(function(){l(this).text(s("updated on ")+b.format(s("HH:MM:ss"))).fadeIn()})},renderBlog:function(){},loadTrace:function(){countLoaded>=totalLoad&&
(this.gotoHash(),clearInterval(iidLoadTrace))},render:function(){var b=this.model.get("PostPublished").total;this.el.html('<article><h2></h2><p></p></article><div class="live-blog"><p class="update-time" id="liveblog-status"></p><div id="liveblog-posts"><ol id="liveblog-post-list" class="liveblog-post-list"></ol></div><div><a id="liveblog-more" href="javascript:void(0)">'+s("More")+"</a></div>");this.limit>=b&&l("#liveblog-more",this.el).hide();this.renderBlog();this.ensureStatus();data=this.model.get("PostPublished")._list;
totalLoad=b=data.length;var c=this,e;iidLoadTrace=setInterval(function(){c.loadTrace()},900);this.views=[];for(this.renderedTotal=b;b--;)data[b].on("rendered",this.renderedOn,this),e=this.addOne(data[b]),this.views.push(e)},renderedOn:function(){this.renderedTotal--;this.renderedTotal||(this.closeAllButFirstWrapup(),this.addClassToHashItem())},closeAllButFirstWrapup:function(b){b=this.views;b.reverse();for(var c=0;c<b.length;c++)l(b[c].el).hasClass("wrapup")&&b[c]._toggleWrap(l(b[c].el))},addClassToHashItem:function(){var b=
window.location.hash.split("#");1<b.length&&l('a[name="'+b[1]+'"]').addClass("hash-open")}});window.livedesk.TimelineView=c;window.livedesk.callback()};window.livedesk.init();
