(function(d){function u(a,c){var b=(a&65535)+(c&65535);return(a>>16)+(c>>16)+(b>>16)<<16|b&65535}function k(a,c,b,i,d,j){a=u(u(c,a),u(i,j));return u(a<<d|a>>>32-d,b)}function m(a,c,b,i,d,j,v){return k(c&b|~c&i,a,c,d,j,v)}function n(a,c,b,i,d,j,v){return k(c&i|b&~i,a,c,d,j,v)}function p(a,c,b,i,d,j,v){return k(b^(c|~i),a,c,d,j,v)}function y(a,c){a[c>>5]|=128<<c%32;a[(c+64>>>9<<4)+14]=c;var b,i,d,j,v,f=1732584193,e=-271733879,g=-1732584194,h=271733878;for(b=0;b<a.length;b+=16)i=f,d=e,j=g,v=h,f=m(f,
e,g,h,a[b],7,-680876936),h=m(h,f,e,g,a[b+1],12,-389564586),g=m(g,h,f,e,a[b+2],17,606105819),e=m(e,g,h,f,a[b+3],22,-1044525330),f=m(f,e,g,h,a[b+4],7,-176418897),h=m(h,f,e,g,a[b+5],12,1200080426),g=m(g,h,f,e,a[b+6],17,-1473231341),e=m(e,g,h,f,a[b+7],22,-45705983),f=m(f,e,g,h,a[b+8],7,1770035416),h=m(h,f,e,g,a[b+9],12,-1958414417),g=m(g,h,f,e,a[b+10],17,-42063),e=m(e,g,h,f,a[b+11],22,-1990404162),f=m(f,e,g,h,a[b+12],7,1804603682),h=m(h,f,e,g,a[b+13],12,-40341101),g=m(g,h,f,e,a[b+14],17,-1502002290),
e=m(e,g,h,f,a[b+15],22,1236535329),f=n(f,e,g,h,a[b+1],5,-165796510),h=n(h,f,e,g,a[b+6],9,-1069501632),g=n(g,h,f,e,a[b+11],14,643717713),e=n(e,g,h,f,a[b],20,-373897302),f=n(f,e,g,h,a[b+5],5,-701558691),h=n(h,f,e,g,a[b+10],9,38016083),g=n(g,h,f,e,a[b+15],14,-660478335),e=n(e,g,h,f,a[b+4],20,-405537848),f=n(f,e,g,h,a[b+9],5,568446438),h=n(h,f,e,g,a[b+14],9,-1019803690),g=n(g,h,f,e,a[b+3],14,-187363961),e=n(e,g,h,f,a[b+8],20,1163531501),f=n(f,e,g,h,a[b+13],5,-1444681467),h=n(h,f,e,g,a[b+2],9,-51403784),
g=n(g,h,f,e,a[b+7],14,1735328473),e=n(e,g,h,f,a[b+12],20,-1926607734),f=k(e^g^h,f,e,a[b+5],4,-378558),h=k(f^e^g,h,f,a[b+8],11,-2022574463),g=k(h^f^e,g,h,a[b+11],16,1839030562),e=k(g^h^f,e,g,a[b+14],23,-35309556),f=k(e^g^h,f,e,a[b+1],4,-1530992060),h=k(f^e^g,h,f,a[b+4],11,1272893353),g=k(h^f^e,g,h,a[b+7],16,-155497632),e=k(g^h^f,e,g,a[b+10],23,-1094730640),f=k(e^g^h,f,e,a[b+13],4,681279174),h=k(f^e^g,h,f,a[b],11,-358537222),g=k(h^f^e,g,h,a[b+3],16,-722521979),e=k(g^h^f,e,g,a[b+6],23,76029189),f=k(e^
g^h,f,e,a[b+9],4,-640364487),h=k(f^e^g,h,f,a[b+12],11,-421815835),g=k(h^f^e,g,h,a[b+15],16,530742520),e=k(g^h^f,e,g,a[b+2],23,-995338651),f=p(f,e,g,h,a[b],6,-198630844),h=p(h,f,e,g,a[b+7],10,1126891415),g=p(g,h,f,e,a[b+14],15,-1416354905),e=p(e,g,h,f,a[b+5],21,-57434055),f=p(f,e,g,h,a[b+12],6,1700485571),h=p(h,f,e,g,a[b+3],10,-1894986606),g=p(g,h,f,e,a[b+10],15,-1051523),e=p(e,g,h,f,a[b+1],21,-2054922799),f=p(f,e,g,h,a[b+8],6,1873313359),h=p(h,f,e,g,a[b+15],10,-30611744),g=p(g,h,f,e,a[b+6],15,-1560198380),
e=p(e,g,h,f,a[b+13],21,1309151649),f=p(f,e,g,h,a[b+4],6,-145523070),h=p(h,f,e,g,a[b+11],10,-1120210379),g=p(g,h,f,e,a[b+2],15,718787259),e=p(e,g,h,f,a[b+9],21,-343485551),f=u(f,i),e=u(e,d),g=u(g,j),h=u(h,v);return[f,e,g,h]}function G(a){var c,b="";for(c=0;c<32*a.length;c+=8)b+=String.fromCharCode(a[c>>5]>>>c%32&255);return b}function C(a){var c,b=[];b[(a.length>>2)-1]=void 0;for(c=0;c<b.length;c+=1)b[c]=0;for(c=0;c<8*a.length;c+=8)b[c>>5]|=(a.charCodeAt(c/8)&255)<<c%32;return b}function H(a,c){var b,
i=C(a),d=[],j=[];d[15]=j[15]=void 0;16<i.length&&(i=y(i,8*a.length));for(b=0;16>b;b+=1)d[b]=i[b]^909522486,j[b]=i[b]^1549556828;b=y(d.concat(C(c)),512+8*c.length);return G(y(j.concat(b),640))}function I(a){var c="",b,i;for(i=0;i<a.length;i+=1)b=a.charCodeAt(i),c+="0123456789abcdef".charAt(b>>>4&15)+"0123456789abcdef".charAt(b&15);return c}function J(a){a=unescape(encodeURIComponent(a));return G(y(C(a),8*a.length))}function K(a,c){var b;if("undefined"==typeof a||"undefined"==typeof c)return!0;for(b in c)if("undefined"==
typeof a[b])return!0;for(b in a)if("undefined"==typeof c[b])return!0;for(b in c)if(c[b])switch(typeof c[b]){case "object":if(K(c[b],a[b]))return!0;break;case "function":if("undefined"==typeof a[b]||c[b].toString()!=a[b].toString())return!0;break;default:if(c[b]!=a[b])return!0}else if(a[b])return!0;return!1}str=function(a){this.init(a)};str.format=function(a){var c=arguments,b=1;2==c.length&&"object"==typeof c[1]&&(c=c[1]);return a.replace(/%?%(?:\(([^\)]+)\))?([disr])/g,function(a,d,j){if(a[0]==a[1])return a.substring(1);
d=c[d||b++];return"undefined"===typeof d?a:"i"==j||"d"==j?+d:d})};str.prototype={init:function(a){this.str=a},format:function(){return str.format(this.str)},toString:function(){return this.str}};d.md5=function(a,c,b){return!c?b?J(a):I(J(a)):b?H(unescape(encodeURIComponent(c)),unescape(encodeURIComponent(a))):I(H(unescape(encodeURIComponent(c)),unescape(encodeURIComponent(a))))};var D={url:"//gravatar.com/avatar/%(md5)s?r=%(rate)s&s=%(size)s&d=%(default)s&%(forcedefault)s",defaults:{rate:"pg",size:48,
"default":encodeURIComponent("images/avatar_default_collaborator.png"),forcedefault:"",key:"Avatar",needle:"Person.EMail"},parse:function(a,c){if(a){c||(c=this.defaults.needle);var b=this,i=c.split("."),l=i[0],j=i[1];d.each(a,function(a,i){a===l&&(void 0!==j&&d.isDefined(i[j]))&&(this[b.defaults.key]=b.get(i[j]));(d.isObject(i)||d.isArray(i))&&b.parse(i,c)});return a}},get:function(a){return"string"!==d.type(a)?a:str.format(this.url,d.extend({},this.defaults,{md5:d.md5(d.trim(a.toLowerCase()))}))}};
d.avatar=D;var r,R=/d{1,4}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|[LloSZ]|"[^"]*"|'[^']*'/g,S=/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g,T=/[^-+\dA-Z]/g,t=function(a,c){a=String(a);for(c=c||2;a.length<c;)a="0"+a;return a};r=function(a,c,b){1==arguments.length&&("[object String]"==Object.prototype.toString.call(a)&&!/\d/.test(a))&&(c=a,a=void 0);a=a?new Date(a):new Date;if(isNaN(a))throw SyntaxError("invalid date");
c=String(r.masks[c]||c||r.masks["default"]);"UTC:"==c.slice(0,4)&&(c=c.slice(4),b=!0);var i=b?"getUTC":"get",d=a[i+"Date"](),j=a[i+"Day"](),k=a[i+"Month"](),f=a[i+"FullYear"](),e=a[i+"Hours"](),g=a[i+"Minutes"](),h=a[i+"Seconds"](),i=a[i+"Milliseconds"](),m=b?0:a.getTimezoneOffset(),n={d:d,dd:t(d),ddd:r.i18n.dayNames[j],dddd:r.i18n.dayNames[j+7],m:k+1,mm:t(k+1),mmm:r.i18n.monthNames[k],mmmm:r.i18n.monthNames[k+12],yy:String(f).slice(2),yyyy:f,h:e%12||12,hh:t(e%12||12),H:e,HH:t(e),M:g,MM:t(g),s:h,
ss:t(h),l:t(i,3),L:t(99<i?Math.round(i/10):i),t:12>e?"a":"p",tt:12>e?"am":"pm",T:12>e?"A":"P",TT:12>e?"AM":"PM",Z:b?"UTC":(String(a).match(S)||[""]).pop().replace(T,""),o:(0<m?"-":"+")+t(100*Math.floor(Math.abs(m)/60)+Math.abs(m)%60,4),S:["th","st","nd","rd"][3<d%10?0:(10!=d%100-d%10)*d%10]};return c.replace(R,function(a){return a in n?n[a]:a.slice(1,a.length-1)})};r.masks={"default":"ddd mmm dd yyyy HH:MM:ss",shortDate:"m/d/yy",mediumDate:"mmm d, yyyy",longDate:"mmmm d, yyyy",fullDate:"dddd, mmmm d, yyyy",
shortTime:"h:MM TT",mediumTime:"h:MM:ss TT",longTime:"h:MM:ss TT Z",isoDate:"yyyy-mm-dd",isoTime:"HH:MM:ss",isoDateTime:"yyyy-mm-dd'T'HH:MM:ss",isoUtcDateTime:"UTC:yyyy-mm-dd'T'HH:MM:ss'Z'"};r.i18n={dayNames:"Sun Mon Tue Wed Thu Fri Sat Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),monthNames:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec January February March April May June July August September October November December".split(" ")};window.livedesk.i18n&&void 0!==window.livedesk.i18n.day_names&&
(r.i18n.dayNames=window.livedesk.i18n.day_names);window.livedesk.i18n&&void 0!==window.livedesk.i18n.month_names&&(r.i18n.monthNames=window.livedesk.i18n.month_names);Date.prototype.format=function(a,c){return r(this,a,c)};Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});Function.prototype.bind||(Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");
var c=Array.prototype.slice.call(arguments,1),b=this,i=function(){},d=function(){return b.apply(this instanceof i?this:a,c.concat(Array.prototype.slice.call(arguments)))};i.prototype=this.prototype;d.prototype=new i;return d});String.prototype.trim||(String.prototype.trim=function(){for(var a=this.replace(/^\s\s*/,""),c=/\s/,b=a.length;c.test(a.charAt(--b)););return a.slice(0,b+1)});var E=!1;this.Class=function(){};Class.extend=function(a,c){function b(){if(!E&&(this._constructor||this._construct))try{return(this._construct||
this._constructor).apply(this,arguments)}catch(a){}}E=!0;var d=new this;E=!1;for(var l in a)d[l]=a[l];b.prototype=d;b.prototype.constructor=b;b.extend=arguments.callee;return b};var L=function(){},q=function(){},M=function(){this.items={}},s=function(){},N=Class.extend({_construct:function(a){this.data=!this.data?{root:""}:this.data;switch(d.type(a)){case "string":this.data.url=a;break;case "array":this.data.url=a[0];void 0!==a[1]&&(this.data.xfilter=url[0]);break;case "object":this.data.url=a.url,
void 0!==a.xfilter&&(this.data.xfilter=a.xfilter)}return this},xfilter:function(){this.data.xfilter=1<arguments.length?d.makeArray(arguments).join(","):d.isArray(arguments[0])?arguments[0].join(","):arguments[0];return this},root:function(a){this.data.root=a;return this},get:function(){return this.data.root+this.data.url},order:function(a,c){this.data.order=c+"="+a;return this},filter:function(a,c){this.data.filter=a+"="+c;return this},decorate:function(a){this.data.url=a.replace(/(%s)/g,this.data.url)},
options:function(){var a={};this.data.xfilter&&(a.headers={"X-Filter":this.data.xfilter});return a}}),w={request:function(a){var c=this,b=function(b,l,j){d.support.cors=!0;a instanceof N?(l=d.extend(!0,{},l,c.options,j,{data:b},a.options()),b=d.ajax(c.href(a.get()),l)):(l=d.extend(!0,{},l,c.options,j,{data:b}),b=d.ajax(c.href(a),l));c.reset();l.fail&&b.fail(l.fail);l.done&&b.done(l.done);l.always&&b.always(l.always);return b};return{read:function(a){return b({},c.readOptions,a)},update:function(a,
d){return b(a,c.updateOptions,d)},insert:function(a,d){return b(a,c.insertOptions,d)},remove:function(a){return b({},c.removeOptions,a)}}},href:function(a){return a},reset:d.noop,options:{},readOptions:{dataType:"json",type:"get",headers:{Accept:"text/json"}},updateOptions:{type:"post",headers:{"X-HTTP-Method-Override":"PUT"}},insertOptions:{dataType:"json",type:"post"},removeOptions:{type:"get",headers:{"X-HTTP-Method-Override":"DELETE"}}},U=0;q.prototype={_changed:!1,_new:!1,defaults:{},data:{},
_construct:function(a,c){this._clientId=U++;this.data={};this.parseHash(a);this._new=!0;var b=this.pushUnique?this.pushUnique():this;b._forDelete=!1;b.clearChangeset();b._clientHash=null;c&&"object"==typeof c&&d.extend(b,c);"object"==typeof a&&(b.parse(a),b._setExpiration());d.isEmptyObject(b.changeset)||b.triggerHandler("update",b.changeset).clearChangeset();return b},syncAdapter:w,feed:function(a,c,b){var a={},b=b?b:this.data,d;for(d in b)a[d]=b[d]instanceof q?c?b[d].feed(c):b[d].relationHash()||
b[d].hash():b[d];return a},sync:function(a,c){var b=this,i=d.Deferred(),l=function(){return b.syncAdapter.request.apply(b.syncAdapter,arguments)};this.hash();b.triggerHandler("sync");if(this._forDelete)return l(a||this.href).remove().done(function(){b._remove()});if(this._clientHash)return l(a||this.href).insert(this.feed()).done(function(a){b._changed=!1;b.parse(a);b._uniq&&b._uniq.replace(b._clientHash,b.hash(),b);b._clientHash=null;b.triggerHandler("insert").Class.triggerHandler("insert",b)});
this._changed?d.isEmptyObject(this.changeset)||(i=this.href&&l(this.href).update(c?this.feed():this.feed("json",!1,this.changeset)).done(function(){b.triggerHandler("update",b.changeset).clearChangeset()})):(!a||!a.force)&&this.exTime&&this.exTime>new Date?b.isDeleted()||b.triggerHandler("update"):i=this.href&&l(this.href).read(a).done(function(a){b.parse(a);b.isDeleted()?b._remove():d.isEmptyObject(b.changeset)?b.clearChangeset().triggerHandler("read"):b.triggerHandler("update",b.changeset).clearChangeset()});
this._setExpiration();return i},_setExpiration:function(){this.exTime=new Date;this.exTime.setSeconds(this.exTime.getSeconds()+5)},_remove:function(){this.triggerHandler("delete");this._uniq&&this._uniq.remove(this.hash())},remove:function(){this._forDelete=!0;return this},isDeleted:function(){return this._forDelete},modelDataBuild:function(a){return a},parse:function(a){a instanceof q&&(a=a.data);if(!a._parsed){for(var c in a){if(this.defaults[c])switch(!0){case "function"===typeof this.defaults[c]&&
void 0===this.data[c]:var b=this.modelDataBuild(new this.defaults[c](a[c]));!this._new&&(b!=this.data[c]&&!(b instanceof s))&&(this.changeset[c]=b);this.data[c]=b;!a[c].href&&this.data[c].relationHash&&this.data[c].relationHash(a[c]);continue;case d.isArray(this.defaults[c]):this.data[c]=this.modelDataBuild(new s(this.defaults[c][0],a[c].href));delete this.data[c];continue;case this.defaults[c]instanceof s:case this.defaults[c]instanceof q:this.data[c]=this.defaults[c];continue}else this._new||("object"===
d.type(a[c])?K(this.data[c],a[c])&&(this.changeset[c]=a[c]):this.data[c]!=a[c]&&(this.changeset[c]=a[c]));"object"===d.type(a[c])&&"object"===d.type(this.data[c])?d.extend(!0,this.data[c],a[c]):this.data[c]=a[c]}this._new=!1;a._parsed=!0}},parseHash:function(a){"string"==typeof a?this.href=a:a&&void 0!==a.href?(this.href=a.href,delete a.href):a&&(void 0!==a.id&&void 0!==this.url)&&(this.href=this.url+a.id);return this},clearChangeset:function(){this._changed=!1;this.changeset={};return this},get:function(a){return this.data[a]},
set:function(a,c,b){var i={};"string"===d.type(a)?i[a]=c:(i=a,b=c);b=d.extend({},{silent:!1},b);this.clearChangeset().parse(i);this._changed=!0;d.isEmptyObject(this.changeset)||b.silent||this.triggerHandler("set",this.changeset);return this},_getClientHash:function(){this._clientHash||(this._clientHash="mcid-"+String(this._clientId));return this._clientHash},hash:function(){!this.href&&this.data.href&&(this.href=this.data.href);return this.data.href||this.href||this._getClientHash()},relationHash:function(a){a&&
(this.data.Id=a);return this.data.Id},off:function(a,c){d(this).off(a,c);return this},on:function(a,c,b){if(void 0===b)d(this).on(a,c);else d(this).on(a,function(){c.apply(b,arguments)});return this},trigger:function(a,c){d(this).trigger(a,c);return this},triggerHandler:function(a,c){d(this).triggerHandler(a,c);return this}};M.prototype={items:{},garbageTime:1500,refresh:function(a){a._exTime||(a._exTime=new Date);a._exTime.setTime(a._exTime.getTime()+this.garbageTime)},set:function(a,c){var b=this;
d(c).on("sync get get-prop set-prop",function(){b.refresh(this)});b.refresh(c);this.items[a]||(this.items[a]=c);return this.items[a]},replace:function(a,c,b){delete this.items[a];return this.set(c,b)},garbage:function(){for(var a in this.items)this.items[a]._exTime&&this.items[a]._exTime<new Date&&(d(this.items[a]).triggerHandler("garbage"),delete this.items[a])},remove:function(a){delete this.items[a]}};var x=q.options={},O,P;q.extend=O=function(a,c){var b;b=Class.extend.call(this,a);b.extend=O;
b.prototype.Class=b;b.on=function(a,c,j){d(b).on(a,function(){c.apply(j,arguments)});return b};b.off=function(a,c){d(b).off(a,c);return b};b.triggerHandler=function(a,c){d(b).triggerHandler(a,c)};c&&c.register&&(L[c.register]=b,delete c.register);b.prototype.options=d.extend({},c);return b};s.prototype={_list:[],getList:function(){return this._list},count:function(){return this._list.length},_construct:function(){this.model||(this.model=q);this._list=[];this.desynced=!0;var a=buildOptions=function(){void 0},
c;for(c in arguments)switch(d.type(arguments[c])){case "function":this.model=arguments[c];break;case "string":this.href=arguments[c];break;case "array":a=function(a){return function(){this._list=this.parse(a)}}(arguments[c]);break;case "object":buildOptions=function(a){return function(){this.options=a;a.href&&(this.href=a.href)}}(arguments[c])}buildOptions.call(this);a.call(this);x=d.extend({},{init:!0},this.options);x.init&&this.init.apply(this,arguments)},init:function(){},get:function(a){var c=
d.Deferred(),b=this;searchKey=function(){for(var d=0;d<b._list.length;d++)if(a==b._list[d].hash()||a==b._list[d].relationHash())return c.resolve(b._list[d]);c.reject()};this.desynced&&this.sync().done(function(){c.resolve(searchKey())})?c:searchKey();return c},remove:function(a){for(var c in this._list)if(a==this._list[c].hash()||a==this._list[c].relationHash()){Array.prototype.splice.call(this._list,c,1);break}return this},syncAdapter:w,setHref:function(a){this.href=a;return this},each:function(a){d.each(this._list,
a)},forwardEach:function(a,c){this._list.forEach(a,c)},reverseEach:function(a,c){for(var b=this._list.length;0<b;++b)a.call(c||this,this[b],b,this)},feed:function(a,c){var b=[],d;for(d in this._list)b[d]=this._list[d].feed(a,c);return b},sync:function(a){var c=this;return this.href&&this.syncAdapter.request.call(this.syncAdapter,this.href).read(a).done(function(a){for(var a=c.parse(a),i=[],l=c._list.length,j=0;j<a.list.length;j++){for(var k=!1,f=0;f<l;f++)if(a.list[j].hash()==c._list[f].hash()){k=
a.list[j];break}if(k)if(k.isDeleted())k._remove();else k.on("delete",function(){c.remove(this.hash())}).on("garbage",function(){this.desynced=!0});else c._list.push(a.list[j]),i.push(a.list[j])}c.desynced=!1;0===l?c.triggerHandler("read"):d(c).triggerHandler("update",[i])})},modelDataBuild:function(a){return a},parse:function(a){if(a.parsed)return a.parsed;var c;c=a;if(!Array.isArray(a))for(b in a)if(d.isArray(a[b])){c=a[b];break}list=[];for(var b in c)c.hasOwnProperty(b)&&list.push(this.modelDataBuild(new this.model(c[b])));
a.parsed={list:list,total:a.total};return a.parsed},insert:function(a){this.desynced=!1;a instanceof q||(a=new this.model(a));this._list.push(a);a.hash();return a.sync(this.href)},off:function(a,c){d(this).off(a,c);return this},on:function(a,c,b){if(void 0===b)d(this).on(a,c);else d(this).on(a,function(){c.apply(b,arguments)});return this},trigger:function(a,c){d(this).trigger(a,c);return this},triggerHandler:function(a,c){d(this).triggerHandler(a,c);return this}};s.extend=P=function(a){a=Class.extend.call(this,
a);a.extend=P;x&&x.register&&(s[x.register]=a);return a};var D=Class.extend({getProperty:function(a){return!this[a]?null:"function"===typeof this[a]?this[a]():this[a]}}).extend({tagName:"div",attributes:{className:"",id:""},namespace:"view",_constructor:function(a,c){d.extend(this,a);c=d.extend({},{init:!0,events:!0,ensure:!0},c);c.ensure&&this._ensureElement();c.init&&this.init.apply(this,arguments);c.events&&this.delegateEvents()},_ensureElement:function(){var a=this.attributes.className,c=this.attributes.id,
b="";d(this.el).length?this.el=d(this.el):("string"===d.type(this.el)&&("."==this.el[0]&&(a+=this.el.substr(0,1)),"#"==this.el[0]&&(c=this.el.substr(0,1))),b="<"+this.tagName,""!==a&&(b=b+' class="'+a+'"'),""!==c&&(b=b+' id="'+c+'"'),b=b+"></"+this.tagName+">",this.el=d(b))},init:function(){return this},resetEvents:function(){this.undelegateEvents();this.delegateEvents()},delegateEvents:function(a){if(a||(a=this.getProperty("events")))for(var c in a){var b=a[c],i;for(i in b){var k=b[i];if("string"===
typeof k&&d.isFunction(this[k]))d(this.el).on(this.getEvent(i),c,this[k].bind(this))}}},getEvent:function(a){return a+this.getNamespace()},getNamespace:function(){return"."+this.getProperty("namespace")},undelegateEvents:function(){d(this.el).off(this.getProperty("namespace"))},render:function(){this.delegateEvents();return this},remove:function(){d(this.el).remove();this.destroy();return this},destroy:function(){this.model&&this.model.trigger("destroy");this.collection&&this.collection.trigger("destroy");
return this},checkElement:function(){return void 0===this.el?!1:void 0!==this.el.selector&&""!=this.el.selector?1===d(this.el.selector).length:1===d(this.el).length},setElement:function(a){this.undelegateEvents();var a=d(a),c=this.el.data();this.el.replaceWith(a);this.el=a;this.el.data(c);this.delegateEvents();return this},resetElement:function(a){this.el=d(a);this._ensureElement();this.delegateEvents()}}),Q=q,F=s,w=d.extend({},w,{reset:function(){try{delete this.options.headers["X-Filter"],delete this.options.data["CId.since"],
delete this.options.data.offset,delete this.options.data.limit}catch(a){}}}),V=function(){var a=this;AuthApp.success=function(){a.options.headers.Authorization=localStorage.getItem("superdesk.login.session")};AuthApp.require.apply(a,arguments)},z=d.extend({},w,{options:{headers:{Authorization:localStorage.getItem("superdesk.login.session")},fail:function(a){401==a.status&&V.apply(z,arguments);404==a.status&&ErrorApp.require.apply(this,arguments)}},href:function(a){return-1===a.indexOf("my/")?a.replace("resources/",
"resources/my/"):a}}),A=function(){this.syncAdapter.options.headers||(this.syncAdapter.options.headers={});this.syncAdapter.options.headers["X-Filter"]=1<arguments.length?d.makeArray(arguments).join(","):d.isArray(arguments[0])?arguments[0].join(","):arguments[0];return this},B=function(a){a?d.extend(!0,this.syncAdapter.options,{data:{"CId.since":a}}):delete this.syncAdapter.options.data["CId.since"];return this},q=Q.extend({isDeleted:function(){return this._forDelete||this.data.DeletedOn},syncAdapter:w,
xfilter:A,since:B}),W=q.extend({syncAdapter:z,xfilter:A,since:B}),s=F.extend({xfilter:A,since:B,asc:function(a){d.extend(!0,this.syncAdapter.options,{data:{asc:a}});return this},desc:function(a){d.extend(!0,this.syncAdapter.options,{data:{desc:a}});return this},limit:function(a){d.extend(!0,this.syncAdapter.options,{data:{limit:a}});return this},offset:function(a){d.extend(!0,this.syncAdapter.options,{data:{offset:a}});return this},syncAdapter:w}),F=s.extend({xfilter:A,since:B,syncAdapter:z});q.extend=
function(){var a=Q.extend.apply(this,arguments),c=new M;d.extend(a.prototype,{_uniq:c,pushUnique:function(){return c.set(this.hash(),this)}},arguments[0]);return a};d.gizmo={Model:q,AuthModel:W,Collection:s,AuthCollection:F,Sync:w,AuthSync:z,View:D,Url:N,Register:L}})(jQuery);
