window.livedesk._=function(j){return window.livedesk.i18n&&void 0!==window.livedesk.i18n[j]?window.livedesk.i18n[j]:j};
window.livedesk.loadGizmo=function(j){var q=this;(function(d){function p(b,f){var c=(b&65535)+(f&65535);return(b>>16)+(f>>16)+(c>>16)<<16|c&65535}function r(b,f,c,a,e,d){b=p(p(f,b),p(a,d));return p(b<<e|b>>>32-e,c)}function a(b,f,c,a,e,d,n){return r(f&c|~f&a,b,f,e,d,n)}function e(b,f,c,a,e,d,n){return r(f&a|c&~a,b,f,e,d,n)}function n(b,f,c,a,e,d,n){return r(c^(f|~a),b,f,e,d,n)}function B(b,f){b[f>>5]|=128<<f%32;b[(f+64>>>9<<4)+14]=f;var c,d,m,j,B,h=1732584193,g=-271733879,k=-1732584194,l=271733878;
for(c=0;c<b.length;c+=16)d=h,m=g,j=k,B=l,h=a(h,g,k,l,b[c],7,-680876936),l=a(l,h,g,k,b[c+1],12,-389564586),k=a(k,l,h,g,b[c+2],17,606105819),g=a(g,k,l,h,b[c+3],22,-1044525330),h=a(h,g,k,l,b[c+4],7,-176418897),l=a(l,h,g,k,b[c+5],12,1200080426),k=a(k,l,h,g,b[c+6],17,-1473231341),g=a(g,k,l,h,b[c+7],22,-45705983),h=a(h,g,k,l,b[c+8],7,1770035416),l=a(l,h,g,k,b[c+9],12,-1958414417),k=a(k,l,h,g,b[c+10],17,-42063),g=a(g,k,l,h,b[c+11],22,-1990404162),h=a(h,g,k,l,b[c+12],7,1804603682),l=a(l,h,g,k,b[c+13],12,
-40341101),k=a(k,l,h,g,b[c+14],17,-1502002290),g=a(g,k,l,h,b[c+15],22,1236535329),h=e(h,g,k,l,b[c+1],5,-165796510),l=e(l,h,g,k,b[c+6],9,-1069501632),k=e(k,l,h,g,b[c+11],14,643717713),g=e(g,k,l,h,b[c],20,-373897302),h=e(h,g,k,l,b[c+5],5,-701558691),l=e(l,h,g,k,b[c+10],9,38016083),k=e(k,l,h,g,b[c+15],14,-660478335),g=e(g,k,l,h,b[c+4],20,-405537848),h=e(h,g,k,l,b[c+9],5,568446438),l=e(l,h,g,k,b[c+14],9,-1019803690),k=e(k,l,h,g,b[c+3],14,-187363961),g=e(g,k,l,h,b[c+8],20,1163531501),h=e(h,g,k,l,b[c+13],
5,-1444681467),l=e(l,h,g,k,b[c+2],9,-51403784),k=e(k,l,h,g,b[c+7],14,1735328473),g=e(g,k,l,h,b[c+12],20,-1926607734),h=r(g^k^l,h,g,b[c+5],4,-378558),l=r(h^g^k,l,h,b[c+8],11,-2022574463),k=r(l^h^g,k,l,b[c+11],16,1839030562),g=r(k^l^h,g,k,b[c+14],23,-35309556),h=r(g^k^l,h,g,b[c+1],4,-1530992060),l=r(h^g^k,l,h,b[c+4],11,1272893353),k=r(l^h^g,k,l,b[c+7],16,-155497632),g=r(k^l^h,g,k,b[c+10],23,-1094730640),h=r(g^k^l,h,g,b[c+13],4,681279174),l=r(h^g^k,l,h,b[c],11,-358537222),k=r(l^h^g,k,l,b[c+3],16,-722521979),
g=r(k^l^h,g,k,b[c+6],23,76029189),h=r(g^k^l,h,g,b[c+9],4,-640364487),l=r(h^g^k,l,h,b[c+12],11,-421815835),k=r(l^h^g,k,l,b[c+15],16,530742520),g=r(k^l^h,g,k,b[c+2],23,-995338651),h=n(h,g,k,l,b[c],6,-198630844),l=n(l,h,g,k,b[c+7],10,1126891415),k=n(k,l,h,g,b[c+14],15,-1416354905),g=n(g,k,l,h,b[c+5],21,-57434055),h=n(h,g,k,l,b[c+12],6,1700485571),l=n(l,h,g,k,b[c+3],10,-1894986606),k=n(k,l,h,g,b[c+10],15,-1051523),g=n(g,k,l,h,b[c+1],21,-2054922799),h=n(h,g,k,l,b[c+8],6,1873313359),l=n(l,h,g,k,b[c+15],
10,-30611744),k=n(k,l,h,g,b[c+6],15,-1560198380),g=n(g,k,l,h,b[c+13],21,1309151649),h=n(h,g,k,l,b[c+4],6,-145523070),l=n(l,h,g,k,b[c+11],10,-1120210379),k=n(k,l,h,g,b[c+2],15,718787259),g=n(g,k,l,h,b[c+9],21,-343485551),h=p(h,d),g=p(g,m),k=p(k,j),l=p(l,B);return[h,g,k,l]}function m(b){var f,c="";for(f=0;f<32*b.length;f+=8)c+=String.fromCharCode(b[f>>5]>>>f%32&255);return c}function J(b){var f,c=[];c[(b.length>>2)-1]=void 0;for(f=0;f<c.length;f+=1)c[f]=0;for(f=0;f<8*b.length;f+=8)c[f>>5]|=(b.charCodeAt(f/
8)&255)<<f%32;return c}function v(b){var f="",c,a;for(a=0;a<b.length;a+=1)c=b.charCodeAt(a),f+="0123456789abcdef".charAt(c>>>4&15)+"0123456789abcdef".charAt(c&15);return f}function D(b){b=unescape(encodeURIComponent(b));return m(B(J(b),8*b.length))}function C(b,f){var c=unescape(encodeURIComponent(b)),a=unescape(encodeURIComponent(f)),e=J(c),d=[],n=[];d[15]=n[15]=void 0;16<e.length&&(e=B(e,8*c.length));for(c=0;16>c;c+=1)d[c]=e[c]^909522486,n[c]=e[c]^1549556828;a=B(d.concat(J(a)),512+8*a.length);return m(B(n.concat(a),
640))}function s(b,f){var c;if("undefined"==typeof b||"undefined"==typeof f)return!0;for(c in f)if("undefined"==typeof b[c])return!0;for(c in b)if("undefined"==typeof f[c])return!0;for(c in f)if(f[c])switch(typeof f[c]){case "object":if(s(f[c],b[c]))return!0;break;case "function":if("undefined"==typeof b[c]||f[c].toString()!=b[c].toString())return!0;break;default:if(f[c]!=b[c])return!0}else if(b[c])return!0;return!1}str=function(b){this.init(b)};str.format=function(b){var f=arguments,c=1;2==f.length&&
"object"==typeof f[1]&&(f=f[1]);return b.replace(/%?%(?:\(([^\)]+)\))?([disr])/g,function(b,a,e){if(b[0]==b[1])return b.substring(1);a=f[a||c++];return"undefined"===typeof a?b:"i"==e||"d"==e?+a:a})};str.prototype={init:function(b){this.str=b},format:function(){return str.format(this.str)},toString:function(){return this.str}};d.md5=function(b,f,c){return!f?c?D(b):v(D(b)):c?C(f,b):v(C(f,b))};var y={url:"//gravatar.com/avatar/%(md5)s?r=%(rate)s&s=%(size)s&d=%(default)s&%(forcedefault)s",defaults:{rate:"pg",
size:48,"default":encodeURIComponent("images/avatar_default_collaborator.png"),forcedefault:"",key:"Avatar",needle:"Person.EMail"},parse:function(b,f){if(b){f||(f=this.defaults.needle);var c=this,a=f.split("."),e=a[0],n=a[1];d.each(b,function(b,a){b===e&&(void 0!==n&&d.isDefined(a[n]))&&(this[c.defaults.key]=c.get(a[n]));(d.isObject(a)||d.isArray(a))&&c.parse(a,f)});return b}},get:function(b){return"string"!==d.type(b)?b:str.format(this.url,d.extend({},this.defaults,{md5:d.md5(d.trim(b.toLowerCase()))}))}};
d.avatar=y;var u,U=/d{1,4}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|[LloSZ]|"[^"]*"|'[^']*'/g,V=/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g,W=/[^-+\dA-Z]/g,x=function(b,f){b=String(b);for(f=f||2;b.length<f;)b="0"+b;return b};u=function(b,f,c){1==arguments.length&&("[object String]"==Object.prototype.toString.call(b)&&!/\d/.test(b))&&(f=b,b=void 0);b=b?new Date(b):new Date;if(isNaN(b))throw SyntaxError("invalid date");
f=String(u.masks[f]||f||u.masks["default"]);"UTC:"==f.slice(0,4)&&(f=f.slice(4),c=!0);var a=c?"getUTC":"get",e=b[a+"Date"](),d=b[a+"Day"](),n=b[a+"Month"](),h=b[a+"FullYear"](),g=b[a+"Hours"](),k=b[a+"Minutes"](),l=b[a+"Seconds"](),a=b[a+"Milliseconds"](),m=c?0:b.getTimezoneOffset(),j={d:e,dd:x(e),ddd:u.i18n.dayNames[d],dddd:u.i18n.dayNames[d+7],m:n+1,mm:x(n+1),mmm:u.i18n.monthNames[n],mmmm:u.i18n.monthNames[n+12],yy:String(h).slice(2),yyyy:h,h:g%12||12,hh:x(g%12||12),H:g,HH:x(g),M:k,MM:x(k),s:l,
ss:x(l),l:x(a,3),L:x(99<a?Math.round(a/10):a),t:12>g?"a":"p",tt:12>g?"am":"pm",T:12>g?"A":"P",TT:12>g?"AM":"PM",Z:c?"UTC":(String(b).match(V)||[""]).pop().replace(W,""),o:(0<m?"-":"+")+x(100*Math.floor(Math.abs(m)/60)+Math.abs(m)%60,4),S:["th","st","nd","rd"][3<e%10?0:(10!=e%100-e%10)*e%10]};return f.replace(U,function(b){return b in j?j[b]:b.slice(1,b.length-1)})};u.masks={"default":"ddd mmm dd yyyy HH:MM:ss",shortDate:"m/d/yy",mediumDate:"mmm d, yyyy",longDate:"mmmm d, yyyy",fullDate:"dddd, mmmm d, yyyy",
shortTime:"h:MM TT",mediumTime:"h:MM:ss TT",longTime:"h:MM:ss TT Z",isoDate:"yyyy-mm-dd",isoTime:"HH:MM:ss",isoDateTime:"yyyy-mm-dd'T'HH:MM:ss",isoUtcDateTime:"UTC:yyyy-mm-dd'T'HH:MM:ss'Z'"};u.i18n={dayNames:"Sun Mon Tue Wed Thu Fri Sat Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),monthNames:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec January February March April May June July August September October November December".split(" ")};window.livedesk.i18n&&void 0!==window.livedesk.i18n.day_names&&
(u.i18n.dayNames=window.livedesk.i18n.day_names);window.livedesk.i18n&&void 0!==window.livedesk.i18n.month_names&&(u.i18n.monthNames=window.livedesk.i18n.month_names);Date.prototype.format=function(b,f){return u(this,b,f)};Array.isArray||(Array.isArray=function(b){return"[object Array]"===Object.prototype.toString.call(b)});Function.prototype.bind||(Function.prototype.bind=function(b){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");
var f=Array.prototype.slice.call(arguments,1),c=this,a=function(){},e=function(){return c.apply(this instanceof a?this:b,f.concat(Array.prototype.slice.call(arguments)))};a.prototype=this.prototype;e.prototype=new a;return e});String.prototype.trim||(String.prototype.trim=function(){for(var b=this.replace(/^\s\s*/,""),f=/\s/,c=b.length;f.test(b.charAt(--c)););return b.slice(0,c+1)});var K=!1;this.Class=function(){};Class.extend=function(b,f){function c(){if(!K&&(this._constructor||this._construct))try{return(this._construct||
this._constructor).apply(this,arguments)}catch(b){}}K=!0;var a=new this;K=!1;for(var e in b)a[e]=b[e];c.prototype=a;c.prototype.constructor=c;c.extend=arguments.callee;return c};var O=function(){},t=function(){},P=function(){this.items={}},w=function(){},Q=Class.extend({_construct:function(b){this.data=!this.data?{root:""}:this.data;switch(d.type(b)){case "string":this.data.url=b;break;case "array":this.data.url=b[0];void 0!==b[1]&&(this.data.xfilter=url[0]);break;case "object":this.data.url=b.url,
void 0!==b.xfilter&&(this.data.xfilter=b.xfilter)}return this},xfilter:function(){this.data.xfilter=1<arguments.length?d.makeArray(arguments).join(","):d.isArray(arguments[0])?arguments[0].join(","):arguments[0];return this},root:function(b){this.data.root=b;return this},get:function(){return this.data.root+this.data.url},order:function(b,f){this.data.order=f+"="+b;return this},filter:function(b,f){this.data.filter=b+"="+f;return this},decorate:function(b){this.data.url=b.replace(/(%s)/g,this.data.url)},
options:function(){var b={};this.data.xfilter&&(b.headers={"X-Filter":this.data.xfilter});return b}}),z={request:function(b){var f=this,c=function(c,a,e){d.support.cors=!0;b instanceof Q?(a=d.extend(!0,{},a,f.options,e,{data:c},b.options()),c=d.ajax(f.href(b.get()),a)):(a=d.extend(!0,{},a,f.options,e,{data:c}),c=d.ajax(f.href(b),a));f.reset();a.fail&&c.fail(a.fail);a.done&&c.done(a.done);a.always&&c.always(a.always);return c};return{read:function(b){return c({},f.readOptions,b)},update:function(b,
a){return c(b,f.updateOptions,a)},insert:function(b,a){return c(b,f.insertOptions,a)},remove:function(b){return c({},f.removeOptions,b)}}},href:function(b){return b},reset:d.noop,options:{},readOptions:{dataType:"json",type:"get",headers:{Accept:"text/json"}},updateOptions:{type:"post",headers:{"X-HTTP-Method-Override":"PUT"}},insertOptions:{dataType:"json",type:"post"},removeOptions:{type:"get",headers:{"X-HTTP-Method-Override":"DELETE"}}},X=0;t.prototype={_changed:!1,_new:!1,defaults:{},data:{},
_construct:function(b,f){this._clientId=X++;this.data={};this.parseHash(b);this._new=!0;var c=this.pushUnique?this.pushUnique():this;c._forDelete=!1;c.clearChangeset();c._clientHash=null;f&&"object"==typeof f&&d.extend(c,f);"object"==typeof b&&c._parse(b);c._setExpiration();c.isDeleted()?c._remove():d.isEmptyObject(c.changeset)?c.clearChangeset().triggerHandler("read"):c.triggerHandler("update",c.changeset).clearChangeset();return c},syncAdapter:z,feed:function(b,f,c){var b={},c=c?c:this.data,a;for(a in c)b[a]=
c[a]instanceof t?f?c[a].feed(f):c[a].relationHash()||c[a].hash():c[a];return b},sync:function(b,a){var c=this,e=d.Deferred(),n=function(){return c.syncAdapter.request.apply(c.syncAdapter,arguments)};this.hash();c.triggerHandler("sync");if(this._forDelete)return n(b||this.href).remove().done(function(){c._remove()});if(this._clientHash)return n(b||this.href).insert(this.feed()).done(function(b){c._changed=!1;c._parse(b);c._uniq&&c._uniq.replace(c._clientHash,c.hash(),c);c._clientHash=null;c.triggerHandler("insert").Class.triggerHandler("insert",
c)});this._changed?d.isEmptyObject(this.changeset)||(e=this.href&&n(this.href).update(a?this.feed():this.feed("json",!1,this.changeset)).done(function(){c.triggerHandler("update",c.changeset).clearChangeset()})):(!b||!b.force)&&this.exTime&&this.exTime>new Date?c.isDeleted()||c.triggerHandler("update"):e=this.href&&n(this.href).read(b).done(function(b){c._parse(b);c.isDeleted()?c._remove():d.isEmptyObject(c.changeset)?c.clearChangeset().triggerHandler("read"):c.triggerHandler("update",c.changeset).clearChangeset()});
this._setExpiration();return e},_setExpiration:function(){this.exTime=new Date;this.exTime.setSeconds(this.exTime.getSeconds()+5)},_remove:function(){this.triggerHandler("delete");this._uniq&&this._uniq.remove(this.hash())},remove:function(){this._forDelete=!0;return this},isDeleted:function(){return this._forDelete},modelDataBuild:function(b){return b},parse:function(b){return b},_parse:function(b){b=b instanceof t?b.data:this.parse(b);if(!b._parsed){for(var a in b){if(this.defaults[a])switch(!0){case "function"===
typeof this.defaults[a]&&void 0===this.data[a]:var c=this.modelDataBuild(new this.defaults[a](b[a]));!this._new&&(c!=this.data[a]&&!(c instanceof w))&&(this.changeset[a]=c);this.data[a]=c;!b[a].href&&this.data[a].relationHash&&this.data[a].relationHash(b[a]);continue;case d.isArray(this.defaults[a]):this.data[a]=this.modelDataBuild(new w(this.defaults[a][0],b[a].href));delete this.data[a];continue;case this.defaults[a]instanceof w:case this.defaults[a]instanceof t:this.data[a]=this.defaults[a];continue}else this._new||
("object"===d.type(b[a])?s(this.data[a],b[a])&&(this.changeset[a]=b[a]):this.data[a]!=b[a]&&(this.changeset[a]=b[a]));"object"===d.type(b[a])&&"object"===d.type(this.data[a])?d.extend(!0,this.data[a],b[a]):this.data[a]=b[a]}this._new=!1;b._parsed=!0}},parseHash:function(b){if(b instanceof t)return this;"string"==typeof b?this.href=b:b&&void 0!==b.href?(this.href=b.href,delete b.href):b&&(void 0!==b.id&&void 0!==this.url)&&(this.href=this.url+b.id);return this},clearChangeset:function(){this._changed=
!1;this.changeset={};return this},get:function(b){return this.data[b]},set:function(b,a,c){var e={};"string"===d.type(b)?e[b]=a:(e=b,c=a);c=d.extend({},{silent:!1},c);this.clearChangeset()._parse(e);this._changed=!0;d.isEmptyObject(this.changeset)||c.silent||this.triggerHandler("set",this.changeset);return this},_getClientHash:function(){this._clientHash||(this._clientHash="mcid-"+String(this._clientId));return this._clientHash},hash:function(){!this.href&&this.data.href&&(this.href=this.data.href);
return this.data.href||this.href||this._getClientHash()},relationHash:function(b){b&&(this.data.Id=b);return this.data.Id},off:function(b,a){d(this).off(b,a);return this},on:function(b,a,c){if(void 0===c)d(this).off(b,a),d(this).on(b,a);else d(this).on(b,function(){a.apply(c,arguments)});return this},one:function(b,a,c){if(void 0===c)d(this).off(b,a),d(this).one(b,a);else d(this).one(b,function(){a.apply(c,arguments)});return this},trigger:function(b,a){d(this).trigger(b,a);return this},triggerHandler:function(b,
a){d(this).triggerHandler(b,a);return this}};P.prototype={items:{},garbageTime:1500,refresh:function(b){b._exTime||(b._exTime=new Date);b._exTime.setTime(b._exTime.getTime()+this.garbageTime)},set:function(b,a){var c=this;d(a).on("sync get get-prop set-prop",function(){c.refresh(this)});c.refresh(a);this.items[b]||(this.items[b]=a);return this.items[b]},replace:function(b,a,c){delete this.items[b];return this.set(a,c)},garbage:function(){for(var b in this.items)this.items[b]._exTime&&this.items[b]._exTime<
new Date&&(d(this.items[b]).triggerHandler("garbage"),delete this.items[b])},remove:function(b){delete this.items[b]}};var E=t.options={},R,S;t.extend=R=function(b,a){var c;c=Class.extend.call(this,b);c.extend=R;c.prototype.Class=c;c.on=function(b,a,f){d(c).on(b,function(){a.apply(f,arguments)});return c};c.off=function(b,a){d(c).off(b,a);return c};c.triggerHandler=function(b,a){d(c).triggerHandler(b,a)};a&&a.register&&(O[a.register]=c,delete a.register);c.prototype.options=d.extend({},a);return c};
w.prototype={_list:[],getList:function(){return this._list},count:function(){return this._list.length},_construct:function(){this.model||(this.model=t);this._list=[];this.desynced=!0;var b=buildOptions=function(){void 0},a;for(a in arguments)switch(d.type(arguments[a])){case "function":this.model=arguments[a];break;case "string":this.href=arguments[a];break;case "array":b=function(b){return function(){this._list=this._parse(b)}}(arguments[a]);break;case "object":buildOptions=function(b){return function(){this.options=
b;b.href&&(this.href=b.href)}}(arguments[a])}buildOptions.call(this);b.call(this);E=d.extend({},{init:!0},this.options);E.init&&this.init.apply(this,arguments)},init:function(){},get:function(b){var a=d.Deferred(),c=this;searchKey=function(){for(var e=0;e<c._list.length;e++)if(b==c._list[e].hash()||b==c._list[e].relationHash())return a.resolve(c._list[e]);a.reject()};this.desynced&&this.sync().done(function(){a.resolve(searchKey())})?a:searchKey();return a},remove:function(b){for(var a in this._list)if(b==
this._list[a].hash()||b==this._list[a].relationHash()){Array.prototype.splice.call(this._list,a,1);break}return this},syncAdapter:z,setHref:function(b){this.href=b;return this},each:function(b){d.each(this._list,b)},forwardEach:function(b,a){this._list.forEach(b,a)},reverseEach:function(b,a){for(var c=this._list.length;0<c;++c)b.call(a||this,this[c],c,this)},feed:function(b,a){var c=[],e;for(e in this._list)c[e]=this._list[e].feed(b,a);return c},sync:function(b){var a=this;return this.href&&this.syncAdapter.request.call(this.syncAdapter,
this.href).read(b).done(function(b){for(var b=a._parse(b),e=[],d=[],n=a._list.length,m=0;m<b.length;m++){for(var h=!1,g=0;g<n;g++)if(b[m].hash()==a._list[g].hash()){h=b[m];break}if(h)if(d.push(h),h.isDeleted())h._remove();else h.on("delete",function(){a.remove(this.hash())}).on("garbage",function(){this.desynced=!0});else b[m].isDeleted()?d.push(b[m]):(a._list.push(b[m]),e.push(b[m]))}a.desynced=!1;0===n?a.triggerHandler("read"):(a.triggerHandler("updates",[d]),a.triggerHandler("addings",[e]))})},
modelDataBuild:function(b){return b},parse:function(b){var a=b;if(!Array.isArray(b))for(i in b)if(d.isArray(b[i])){a=b[i];break}return a},_parse:function(b){if(b._parsed)return b._parsed;var b=this.parse(b),a,c=[],e;for(a in b)b.hasOwnProperty(a)&&(e=new this.model(b[a]),e=this.modelDataBuild(e),c.push(e));b._parsed=c;return b._parsed},insert:function(b){this.desynced=!1;b instanceof t||(b=this.modelDataBuild(new this.model(b)));this._list.push(b);b.hash();return b.sync(this.href)},off:function(b,
a){d(this).off(b,a);return this},on:function(b,a,c){if(void 0===c)d(this).off(b,a),d(this).on(b,a);else d(this).on(b,function(){a.apply(c,arguments)});return this},one:function(b,a,c){if(void 0===c)d(this).off(b,a),d(this).one(b,a);else d(this).one(b,function(){a.apply(c,arguments)});return this},trigger:function(b,a){d(this).trigger(b,a);return this},triggerHandler:function(b,a){d(this).triggerHandler(b,a);return this}};w.extend=S=function(b){b=Class.extend.call(this,b);b.extend=S;E&&E.register&&
(w[E.register]=b);return b};var Y=0,y=Class.extend({getProperty:function(b){return!this[b]?null:"function"===typeof this[b]?this[b]():this[b]}}).extend({tagName:"div",attributes:{className:"",id:""},namespace:"view",_constructor:function(b,a){d.extend(this,b);this._clientId=Y++;a=d.extend({},{init:!0,events:!0,ensure:!0},a);a.ensure&&this._ensureElement();a.init&&this.init.apply(this,arguments);a.events&&this.resetEvents()},_ensureElement:function(){var b=this.attributes.className,a=this.attributes.id,
c="";d(this.el).length?this.el=d(this.el):("string"===d.type(this.el)&&("."==this.el[0]&&(b+=this.el.substr(0,1)),"#"==this.el[0]&&(a=this.el.substr(0,1))),c="<"+this.tagName,""!==b&&(c=c+' class="'+b+'"'),""!==a&&(c=c+' id="'+a+'"'),c=c+"></"+this.tagName+">",this.el=d(c))},init:function(){return this},resetEvents:function(){this.undelegateEvents();this.delegateEvents()},delegateEvents:function(b){if(b||(b=this.getProperty("events")))for(var a in b){var c=b[a],e;for(e in c){var n=c[e];if("string"===
typeof n&&d.isFunction(this[n]))d(this.el).on(this.getEvent(e),a,this[n].bind(this))}}},undelegateEvents:function(){d(this.el).off(this.getNamespace());return this},getEvent:function(b){return b+this.getNamespace()},getNamespace:function(){return"."+this.getProperty("namespace")},render:function(){this.delegateEvents();return this},remove:function(){d(this.el).remove();this.destroy();return this},destroy:function(){this.model&&this.model.trigger("destroy");this.collection&&this.collection.trigger("destroy");
return this},checkElement:function(){return void 0===this.el?!1:void 0!==this.el.selector&&""!=this.el.selector?1===d(this.el.selector).length:d(this.el).is(":visible")},setElement:function(b){this.undelegateEvents();var b=d(b),a=this.el.data();this.el.replaceWith(b);this.el=b;this.el.data(a);this.delegateEvents();return this},resetElement:function(b){this.el=d(b);this._ensureElement();this.delegateEvents()}}),T=t,L=w,z=d.extend({},z,{reset:function(){try{delete this.options.headers["X-Filter"],this.options.data=
{}}catch(b){}}}),Z=function(){AuthApp.success=function(){};AuthApp.require.apply(this,arguments)},F=d.extend({},z,{options:{fail:function(b){401==b.status&&Z.apply(F,arguments);404==b.status&&ErrorApp.require.apply(this,arguments)}},href:function(b){return-1===b.indexOf("my/")?b.replace("resources/","resources/my/"):b}}),G=function(){this.syncAdapter.options.headers||(this.syncAdapter.options.headers={});this._xfilter=1<arguments.length?d.makeArray(arguments).join(","):d.isArray(arguments[0])?arguments[0].join(","):
arguments[0];this.syncAdapter.options.headers["X-Filter"]=this._xfilter;this.syncAdapter.options.headers["X-Format-DateTime"]="M/dd/yyyy HH:mm:ss";return this},A=function(b,a){void 0===b?delete this.syncAdapter.options.data[a]:(void 0===this.syncAdapter.options.data&&(this.syncAdapter.options.data={}),this.syncAdapter.options.data[a]=b);return this},H=function(b,a){void 0===a&&(a="CId");return A.call(this,b,a+".since")},I=function(b,a){void 0===a&&(a="CId");return A.call(this,b,a+".until")},M=function(b,
a){void 0===a&&(a="CId");return A.call(this,b,a+".start")},N=function(b,a){void 0===a&&(a="CId");return A.call(this,b,a+".end")},t=T.extend({isDeleted:function(){return this._forDelete||this.data.DeletedOn},syncAdapter:z,xfilter:G,since:H,until:I,start:M,end:N}),aa=t.extend({syncAdapter:F,xfilter:G,since:H,until:I}),w=L.extend({xfilter:G,since:H,until:I,start:M,end:N,asc:function(b){return A.call(this,b,"asc")},desc:function(b){return A.call(this,b,"desc")},limit:function(b){return A.call(this,b,
"limit")},offset:function(b){return A.call(this,b,"offset")},syncAdapter:z}),L=w.extend({xfilter:G,since:H,until:I,start:M,end:N,syncAdapter:F});t.extend=function(){var b=T.extend.apply(this,arguments),a=new P;d.extend(b.prototype,{_uniq:a,pushUnique:function(){return a.set(this.hash(),this)}},arguments[0]);return b};d.gizmo={Model:t,AuthModel:aa,Collection:w,AuthCollection:L,Sync:z,AuthSync:F,View:y,Url:Q,Register:O};q.preLoad(j)})(jQuery)};
function isOnly(j,q){"string"===$.type(q)&&(q=[q]);var d=0,p=q.length;for(i in j){if(-1===$.inArray(i,q))return!1;d++;if(d>p)return!1}return d===p}var root=this;
window.livedesk.loadXDRequest=function(j){var q=j;root.XDomainRequest&&q.ajaxTransport("+*",function(d){if(d.crossDomain&&d.async){d.timeout&&(d.xdrTimeout=d.timeout,delete d.timeout);var j;return{send:function(r,a){function e(e,d,n,v){j.onload=j.onerror=j.ontimeout=q.noop;j=void 0;a(e,d,n,v)}j=new XDomainRequest;if(d.dataType){var n="";for(i in d.headers)n+=i+"="+encodeURIComponent(d.headers[i])+"&";n=n.replace(/(\s+)?.$/,"");d.url=d.url+(-1===d.url.indexOf("?")?"?":"&")+n}j.open(d.type,d.url);j.onload=
function(){e(200,"OK",{text:j.responseText},"Content-Type: "+j.contentType)};j.onerror=function(){e(404,"Not Found")};d.xdrTimeout&&(j.ontimeout=function(){e(0,"timeout")},j.timeout=d.xdrTimeout);j.send(d.hasContent&&d.data||null)},abort:function(){j&&(j.onerror=q.noop(),j.abort())}}}})};
window.livedesk.init=function(){window.livedesk.location=window.location.href.split("#")[0];var j=this,q=!1,d=!1;contentPath=void 0===j.contentPath?"":j.contentPath;"undefined"==typeof jQuery?q=!0:1.7>parseFloat($().jquery)&&(d=q=!0);q?j.loadScript("//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js",function(){j.loadXDRequest(jQuery);"undefined"==typeof $.gizmo?j.loadGizmo(d):j.preLoad(d)}):(j.loadXDRequest(jQuery),"undefined"==typeof $.gizmo?j.loadGizmo(d):j.preLoad(d))};
window.livedesk.loadScript=function(j,q){var d=document.createElement("script");d.type="text/javascript";d.readyState?d.onreadystatechange=function(){if("loaded"==d.readyState||"complete"==d.readyState)d.onreadystatechange=null,q()}:d.onload=function(){q()};d.src=j;document.getElementsByTagName("head")[0].appendChild(d)};window.livedesk.preLoad=function(j){j?(j=$.noConflict(!0),this.startLoading(j,window.livedesk._)):this.startLoading(jQuery,window.livedesk._)};
window.livedesk.startLoading=function(j,q){var d=j.gizmo.Model.extend({}),d=j.gizmo.Model.extend({defaults:{Creator:d},services:{flickr:!0,google:!0,twitter:!0,facebook:!0,youtube:!0},getClass:function(){switch(this.get("Type").Key){case "wrapup":return"wrapup";case "quote":return"quotation";case "advertisement":return"advertisement";default:return this.isService()?"service":"tw"}},isService:function(){return this.get("AuthorName")in this.services},isQuote:function(){return"quotation"==this.getClass()},
twitter:{link:{anchor:function(a){return a.replace(/[A-Za-z]+:\/\/[A-Za-z0-9-_]+\.[A-Za-z0-9-_:%&\?\/.=]+/g,function(a){a=a.link(a);return a=a.replace('href="','target="_blank" href="')})},user:function(a){return a.replace(/[@]+[A-Za-z0-9-_]+/g,function(a){var d=a.replace("@",""),a=a.link("http://twitter.com/"+d);return a=a.replace('href="','target="_blank" onclick="loadProfile(\''+d+'\');return(false);"  href="')})},tag:function(a){return a.replace(/[#]+[A-Za-z0-9-_]+/g,function(a){var d=a.replace(" #",
" %23"),a=a.link("http://summize.com/search?q="+d);return a=a.replace('href="','target="_blank" href="')})},all:function(a){a=this.anchor(a);a=this.user(a);return a=this.tag(a)}}}});Posts=j.gizmo.Collection.extend({timeInterval:1E4,idInterval:0,_latestCId:0,keep:!1,init:function(){var a=this;this.on("readauto updatesauto read updates addings addingsauto",function(e,d){void 0===d&&(d=a._list);a.getMaximumCid(d)})},destroy:function(){this.stop()},auto:function(){var a=this;ret=this.stop().start();this.idInterval=
setInterval(function(){a.start()},this.timeInterval);return ret},getMaximumCid:function(a){p=0;for(count=a.length;p<count;p++){var e=parseInt(a[p].get("CId"));!isNaN(e)&&this._latestCId<e&&(this._latestCId=e)}},start:function(){var a={data:{"cId.since":this._latestCId},headers:{"X-Filter":this._xfilter,"X-Format-DateTime":"M/dd/yyyy HH:mm:ss"}};0===this._latestCId&&delete a.data;if(!this.keep&&this.view&&!this.view.checkElement())this.stop();else return this.triggerHandler("beforeUpdate"),this.autosync(a)},
stop:function(){clearInterval(this.idInterval);return this},autosync:function(a){var e=this;return this.href&&this.syncAdapter.request.call(this.syncAdapter,this.href).read(a).done(function(a){for(var a=e._parse(a),d=[],m=[],j=e._list.length,q=0;q<a.length;q++){for(var p=!1,r=0;r<j;r++)if(a[q].hash()==e._list[r].hash()){p=a[q];break}if(p)if(m.push(p),p.isDeleted())p._remove();else p.on("delete",function(){e.remove(this.hash())}).on("garbage",function(){this.desynced=!0});else a[q].isDeleted()?m.push(a[q]):
(e._list.push(a[q]),d.push(a[q]))}e.desynced=!1;0===j?e.triggerHandler("readauto"):(e.triggerHandler("updatesauto",[m]),e.triggerHandler("addingsauto",[d]))})}}).extend({parse:function(a){void 0!==a.total&&(a.total=parseInt(a.total),void 0===this.total&&(this.total=a.total),delete a.total);return a.PostList?a.PostList:a},model:d});Blog=j.gizmo.Model.extend({defaults:{PostPublished:Posts}});var p=0,r;r=j.gizmo.View.extend({init:function(){var a=this;a.xfilter="PublishedOn, DeletedOn, Order, Id, CId, Content, CreatedOn, Type, AuthorName, Author.Source.Name, Author.Source.Id, IsModified, AuthorPerson.EMail, AuthorPerson.FirstName, AuthorPerson.LastName, AuthorPerson.Id, Meta";
a.model.on("read update",function(e,d){a.render(e,d)}).on("delete",a.remove,a).xfilter(a.xfilter).sync()},remove:function(){this._parent.removeOne(this);this.el.remove();return this},itemTemplate:function(a,e,d,j){var m="",p=a.getClass(),r=a.get("AuthorName"),D="",C="";if(a.data.hasOwnProperty("Meta")){var s=a.data.Meta;"string"==typeof s&&(s=JSON.parse(s));if(s.hasOwnProperty("annotation"))if("string"===typeof s.annotation){if("<br>"===s.annotation||"<br/>"===s.annotation||"<br />"===s.annotation)s.annotation=
"";C='<div class="editable annotation">'+s.annotation+"</div>"}else if(null!==s.annotation[1]){if("<br>"===s.annotation[0]||"<br/>"===s.annotation[0]||"<br />"===s.annotation[0])s.annotation[0]="";if("<br>"===s.annotation[1]||"<br/>"===s.annotation[1]||"<br />"===s.annotation[1])s.annotation[1]="";D='<div class="editable annotation">'+s.annotation[0]+"</div>";C='<div class="editable annotation">'+s.annotation[1]+"</div>"}else{if("<br>"===s.annotation[0]||"<br/>"===s.annotation[0]||"<br />"===s.annotation[0])s.annotation[0]=
"";C='<div class="editable annotation">'+s.annotation[0]+"</div>"}}avatarString="";"true"!=q("no_avatar")&&(0<j.length&&"twitter"!=r)&&(avatarString='<figure><img src="'+j+'" ></figure>');switch(p){case "tw":case "service":m=m+D+avatarString;m+='<div class="result-content">';"twitter"==r?(m+='<blockquote class="twitter-tweet"><p>'+e+"</p>&mdash; "+s.from_user_name+" (@"+s.from_user_name+') <a href="https://twitter.com/'+s.from_user+"/status/"+s.id_str+'" data-datetime="'+s.created_at+'"></a></blockquote>',
window.livedesk.loadScript("//platform.twitter.com/widgets.js",function(){}),window.livedesk.loadedTweeterScript=!0):"youtube"==r?(m+='<div class="result-text">'+e+"</div>",m+='<p class="attributes"><i class="source-icon"></i> '+q("by")+" ",m+='<a class="author-name" href="http://youtube.com/'+s.uploader+'" target="_blank">'+s.uploader+"</a>"):"google"==r?(m+='<h3><a target="_blank" href="'+s.unescapedUrl+'">'+s.title+"</a></h3>",m+='<div class="result-text">'+e+"</div>",m+='<p class="attributes"><i class="source-icon"></i> '+
q("by")+" "+a.get("AuthorName")):"flickr"==r?(m+='<div class="result-text">'+e+"</div>",m+='<p class="attributes"><i class="source-icon"></i> '+q("by")+" "+a.get("AuthorName")):(m+='<div class="result-text">'+e+"</div>",m+='<p class="attributes"><i class="source-icon"></i> '+q("by")+" "+a.get("AuthorName"),m+="<time>"+d+"</time>");m+="</p>";m+="</div>";m+=C;break;case "quotation":var y,a=a.get("AuthorName"),d=e.split("<div><br><br></div>"),j=e.split("<br><br><br>");2==d.length?(e=d[0],y='<div class="quotation-author">'+
d[1]+"</div>"):2==j.length&&(e=j[0],y='<div class="quotation-author">'+j[1]+"</div>");m+='<div class="result-content">';m+='<div class="result-text">'+e+"</div>";m=y?m+y:m+('<div class="attributes">'+q("by")+" "+a+"</div>");m+="</div>";break;case "wrapup":m+='<span class="big-toggle"></span>';m+="<h3>"+e+"</h3>";break;case "advertisement":m+=e}return m},toggleWrap:function(a,e){"boolean"!=typeof e&&(e=!1);this._toggleWrap(j(a).closest("li").first(),e)},_toggleWrap:function(a){a.hasClass("open")?(a.removeClass("open").addClass("closed"),
a.nextUntil(".wrapup").hide()):(a.removeClass("closed").addClass("open"),a.nextUntil(".wrapup").show())},togglePermalink:function(a){this._togglePermalink(j(a).next('input[data-type="permalink"]'))},_togglePermalink:function(a){"visible"==a.css("visibility")?a.css("visibility","hidden"):a.css("visibility","visible")},render:function(){var a=this,e=parseFloat(a.model.get("Order")),d="";this.model.get("AuthorPerson")&&this.model.get("AuthorPerson").EMail&&(d=j.avatar.get(a.model.get("AuthorPerson").EMail));
!isNaN(a.order)&&e!=a.order&&(a.order=e,a._parent.reorderOne(a));var p=a.model.get("Content"),e="";"wrapup"==a.model.getClass()&&(e+="open ");if(a.model.isService()){var e=e+a.model.get("AuthorName"),m=JSON.parse(a.model.get("Meta")),r=a.model.get("PublishedOn"),r=new Date(r),v=r.format("ddd mmm dd yyyy HH:MM:ss TT");"flickr"==a.model.get("AuthorName")?(p=j("<span>"+p+"</span>"),p.find("img").attr("src",p.find("a").attr("href")),p=p.html()):"twitter"==a.model.get("AuthorName")?(d=m.profile_image_url,
p=a.model.twitter.link.all(p)):"google"==a.model.get("AuthorName")&&m.tbUrl&&(p+='<p><a href="'+m.url+'"><img src="'+m.tbUrl+'" height="'+m.tbHeight+'" width="'+m.tbWidth+'"></a></p>')}r=a.model.get("PublishedOn");r=new Date(r);v=r.format(q("ddd mmm dd yyyy HH:MM:ss TT"));"true"===q("show_current_date")&&(new Date).format("mm dd yyyy")==r.format("mm dd yyyy")&&(v=r.format(q("HH:MM:ss TT")));a.model.get("AuthorName");p=a.itemTemplate(a.model,p,v,d);d=a.model.get("Order");m=a.model.getClass();r=window.livedesk.location+
"#"+a._parent.hashIdentifier+d;v="";"advertisement"!==m&&"wrapup"!==m&&(v='<a rel="bookmark" href="#'+a._parent.hashIdentifier+d+'">#</a><input type="text" value="'+r+'" style="visibility:hidden" data-type="permalink" />');e='<li class="'+e+m+'"><a name="'+d+'"></a>'+p+"&nbsp;"+v+"</li>";"undefined"!=typeof window.livedesk.productionServer&&"undefined"!=typeof window.livedesk.frontendServer&&(re=RegExp(window.livedesk.productionServer,"g"),e=e.replace(re,window.livedesk.frontendServer));a.setElement(e);
a.model.triggerHandler("rendered");j(a.el).off("click.livedesk",".big-toggle").on("click.livedesk",".big-toggle",function(){a.toggleWrap(this,!0)});j(a.el).off("click.livedesk",'a[rel="bookmark"]').on("click.livedesk",'a[rel="bookmark"]',function(){a.togglePermalink(this)});j(a.el).off("click.livedesk",'input[data-type="permalink"]').on("focus.livedesk click.livedesk",'input[data-type="permalink"]',function(){j(this).select()})}});totalLoad=0;d=j.gizmo.View.extend({limit:5,offset:0,hashIdentifier:"livedeskitem=",
el:"#livedesk-root",timeInterval:1E4,idInterval:0,_latestCId:0,events:{"#liveblog-more":{click:"more"}},more:function(a){var e=this;e.model.get("PostPublished");postPublished=e.model.get("PostPublished");e.filters&&j.each(e.filters,function(a,e){postPublished[a].apply(postPublished,e)});postPublished.xfilter(e.xfilter).limit(e.limit).offset(e._views.length).sync().done(function(){var d=e.model.get("PostPublished").total;e._views.length>=d&&j(a.target).hide()})},setIdInterval:function(a){this.idInterval=
setInterval(a,this.timeInterval);return this},pause:function(){clearInterval(this.idInterval);return this},sync:function(){var a=this;this.auto().pause().setIdInterval(function(){a.auto()})},auto:function(){this.model.xfilter().sync({force:!0});return this},ensureStatus:function(){if(this.model.get("ClosedOn")){var a=new Date(this.model.get("ClosedOn"));this.pause();this.model.get("PostPublished").pause();this.el.find("#liveblog-status").html(q("The liveblog coverage was stopped ")+a.format(q("mm/dd/yyyy HH:MM:ss")))}},
gotoHash:function(){if(0<location.hash.length){var a=location.hash;location.hash="";location.hash=a}},init:function(){var a=this;a._views=[];a.rendered=!1;"string"===j.type(a.url)&&(a.model=new Blog(a.url.replace("my/","")));a.xfilter="PublishedOn, DeletedOn, Order, Id, CId, Content, CreatedOn, Type, AuthorName, Author.Source.Name, Author.Source.Id, IsModified, AuthorPerson.EMail, AuthorPerson.FirstName, AuthorPerson.LastName, AuthorPerson.Id, Meta";a.model.on("read",function(){if(!a.rendered){var e,
d=window.location.href.split("#"),j=a.model.get("PostPublished").on("read readauto",a.render,a).on("addings addingsauto",a.addAll,a).on("addingsauto",a.updateTotal,a).on("updates updatesauto",a.updateStatus,a).on("beforeUpdate",a.updateingStatus,a).xfilter(a.xfilter).limit(a.limit);d[1]&&-1!==(e=d[1].indexOf(a.hashIdentifier))?(e=parseFloat(d[1].substr(e+a.hashIdentifier.length)),a.filters={end:[e,"order"]},j.one("rendered",a.showLiner,a).end(e,"order").sync()):j.offset(a.offset).auto()}a.rendered=
!0}).on("update",function(){a.ensureStatus();a.renderBlog()});a.sync()},showLiner:function(){var a=this;j("#liveblog-firstmore").on("click",function(){a.el.find("#liveblog-post-list").html("");p=0;for(count=a._views.length;p<count;p++)a._views[p].rendered=!1;a._views=[];var e=a.model.get("PostPublished");e._list=[];e._latestCId=0;e.limit(a.limit).offset(a.offset).auto();j(this).hide()}).show()},removeOne:function(a){a=this._views.indexOf(a);this.model.get("PostPublished").total--;this._views.splice(a,
1);return this},reorderOne:function(a){this._views.sort(function(a,d){return a.order-d.order});pos=this._views.indexOf(a);0===pos?a.el.insertAfter(this._views[1].el):a.el.insertBefore(this._views[0<pos?pos-1:1].el)},addOne:function(a){var d=new r({model:a,_parent:this}),j=this._views.length;a.postview=d;d.order=parseFloat(a.get("Order"));if(j){var q,m;for(p=0;p<j;p++)if(d.order>this._views[p].order)q=this._views[p],nextIndex=p;else if(d.order<this._views[p].order){m=this._views[p];prevIndex=p;break}m?
(d.el.insertAfter(m.el),this._views.splice(prevIndex,0,d)):q&&(d.el.insertBefore(q.el),this._views.splice(nextIndex+1,0,d))}else this.el.find("#liveblog-post-list").prepend(d.el),this._views=[d];return d},updateTotal:function(a,d){for(var j=d.length;j--;)this.model.get("PostPublished").total++},addAll:function(a,d){for(var j=d.length;j--;)this.addOne(d[j])},updateingStatus:function(){this.el.find("#liveblog-status").html(q("updating..."))},updateStatus:function(){var a=new Date;this.el.find("#liveblog-status").fadeOut(function(){j(this).text(q("updated on ")+
a.format(q("HH:MM:ss"))).fadeIn()})},renderBlog:function(){},render:function(){var a=this.model.get("PostPublished").total;this.el.html('<article><h2></h2><p></p></article><div class="live-blog"><p class="update-time" id="liveblog-status"></p><div class="liveblog-more-container"><a class="liveblog-more" id="liveblog-firstmore" href="javascript:void(0)" style="display:none;">'+q("Load more posts")+'</a></div><div id="liveblog-posts"><ol id="liveblog-post-list" class="liveblog-post-list"></ol></div><div><a id="liveblog-more" class="liveblog-more" href="javascript:void(0)">'+
q("More")+"</a></div>");this.limit>=a&&j("#liveblog-more",this.el).hide();this.renderBlog();this.ensureStatus();data=this.model.get("PostPublished")._list;totalLoad=a=data.length;var d;this.views=[];for(this.renderedTotal=a;a--;)data[a].on("rendered",this.renderedOn,this),d=this.addOne(data[a]),this.views.push(d);this.model.get("PostPublished").triggerHandler("rendered")},renderedOn:function(){this.renderedTotal--;this.renderedTotal||this.closeAllButFirstWrapup()},closeAllButFirstWrapup:function(a){a=
this.views;a.reverse();for(var d=0;d<a.length;d++)j(a[d].el).hasClass("wrapup")&&a[d]._toggleWrap(j(a[d].el))}});window.livedesk.TimelineView=d;window.livedesk.callback()};window.livedesk.init();